/* Inhalte: „Gefühls-Decoder“ (Solo) – kurze Szenen zum Gefühle-Lesen.
   Eigene Texte, angelehnt an die ISA-Materialien „Gefühle erkennen“ und
   „Alles eine Frage der Perspektive“ (mehrere Sichtweisen können stimmen).
   Felder:
     id        eindeutig
     who       Name der Figur (erfunden)
     text      Situation (1–2 kurze Sätze)
     say       was die Person sagt (optional)
     body      Körpersprache (optional)
     answer    wahrscheinlichstes Gefühl
     options   4 Wörter, answer ist dabei
     also      Wörter aus options, die „auch drin“ sind (halbe Punkte, Serie bleibt)
     intensity 1 = leicht, 2 = mittel, 3 = stark
     clue      kurze Erklärung: woran erkennt man es?
     signs     welche Hinweise zählen: koerper | worte | situation
     heikel    nur mit Freigabe der Lehrkraft (Familie, Geld, Aussehen, Verlust, Herkunft) */
(function () {
  const C = (window.CREW.content = window.CREW.content || {});
  C.decoder = [
    { id: 'dc01', who: 'Mia', text: 'Beim Sport werden Teams gewählt. Mia wird als Letzte gewählt.', say: 'Passt schon.', body: 'Sie sagt es leise und schaut auf den Boden.',
      answer: 'Enttäuschung', options: ['Enttäuschung', 'Scham', 'Freude', 'Ekel'], also: ['Scham'], intensity: 2,
      clue: 'Leise Stimme, Blick nach unten: Das tut weh. „Passt schon“ versteckt das Gefühl nur.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc02', who: 'Tiago', text: 'Tiago bekommt seinen Test zurück: 48 von 60 Punkten.', say: 'Ja, Mann! Endlich!', body: 'Er ballt die Faust und grinst breit.',
      answer: 'Stolz', options: ['Stolz', 'Scham', 'Angst', 'Langeweile'], intensity: 3,
      clue: 'Faust und breites Grinsen: Er feiert sich. Er hat etwas selbst geschafft.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc03', who: 'Aylin', text: 'Aylin soll gleich vor der Klasse ein Referat halten.', say: 'Muss ich wirklich als Erste?', body: 'Ihre Hände zittern. Sie zupft an ihrem Ärmel.',
      answer: 'Nervosität', options: ['Nervosität', 'Wut', 'Freude', 'Ekel'], intensity: 2,
      clue: 'Zittern und Zupfen zeigen Anspannung. Vor anderen reden macht fast allen etwas Angst.', signs: ['koerper', 'situation'] },
    { id: 'dc04', who: 'Jeff', text: 'Jeff wartet 20 Minuten auf den Bus. Dann fährt der Bus einfach vorbei.', say: 'Das gibt’s doch nicht!', body: 'Er schreit hinterher und tritt gegen einen Mülleimer.',
      answer: 'Wut', options: ['Wut', 'Trauer', 'Überraschung', 'Stolz'], intensity: 3,
      clue: 'Schreien und Treten: viel Energie im Körper. Das ist Wut, und zwar stark.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc05', who: 'Noah', text: 'Im Klassenchat postet jemand ein altes Kinderfoto von Noah. Alle schicken Lach-Smileys.', say: 'Löscht das. Sofort.', body: 'Sein Gesicht wird rot. Er dreht das Handy um.',
      answer: 'Scham', options: ['Scham', 'Wut', 'Freude', 'Langeweile'], also: ['Wut'], intensity: 3,
      clue: 'Rotes Gesicht, Handy weg: Er will sich verstecken. Wut ist auch dabei, aber Scham ist vorne.', signs: ['koerper', 'situation'] },
    { id: 'dc06', who: 'Sara', text: 'Morgen beginnt Saras erstes Praktikum. In einem Friseursalon.', say: 'Ich hab mir schon drei Outfits rausgelegt!', body: 'Sie redet schnell und hüpft fast dabei.',
      answer: 'Vorfreude', options: ['Vorfreude', 'Nervosität', 'Ekel', 'Trauer'], also: ['Nervosität'], intensity: 3,
      clue: 'Hüpfen und viel planen: Sie freut sich auf etwas, das noch kommt. Das heißt Vorfreude.', signs: ['koerper', 'worte'] },
    { id: 'dc07', who: 'Luca', text: 'Luca hat sein Handy im Bus verloren. Eine Schülerin bringt es ihm zurück.', say: 'Echt jetzt? Du rettest mich!', body: 'Er atmet laut aus und lacht.',
      answer: 'Erleichterung', options: ['Erleichterung', 'Neid', 'Wut', 'Langeweile'], intensity: 3,
      clue: 'Laut ausatmen heißt oft: Die Sorge fällt ab. Das ist Erleichterung.', signs: ['koerper', 'situation'] },
    { id: 'dc08', who: 'Emir', text: 'Emir wollte mit seinem besten Freund auf die Schueberfouer. Der Freund geht jetzt mit anderen.', say: 'Viel Spaß euch. Echt.', body: 'Er lächelt, aber nur mit dem Mund.',
      answer: 'Enttäuschung', options: ['Enttäuschung', 'Eifersucht', 'Freude', 'Ekel'], also: ['Eifersucht'], intensity: 2,
      clue: 'Ein Lächeln nur mit dem Mund ist oft nicht echt. Sein Plan ist geplatzt.', signs: ['koerper', 'situation'] },
    { id: 'dc09', who: 'Yara', text: 'Yara soll im Praktikum einen verstopften Abfluss sauber machen.', say: 'Das riecht wie ein drei Wochen alter Döner.', body: 'Sie hält sich die Nase zu und dreht den Kopf weg.',
      answer: 'Ekel', options: ['Ekel', 'Stolz', 'Trauer', 'Vorfreude'], intensity: 2,
      clue: 'Nase zu, Kopf weg: typisch Ekel. Ihr Witz zeigt aber: Sie kommt damit klar.', signs: ['koerper', 'worte'] },
    { id: 'dc10', who: 'Dylan', text: 'Dylan kommt in die Klasse. Alle springen auf und singen für ihn.', say: 'Was? Woher wisst ihr das?', body: 'Seine Augen werden groß. Er bleibt in der Tür stehen.',
      answer: 'Überraschung', options: ['Überraschung', 'Freude', 'Angst', 'Ekel'], also: ['Freude'], intensity: 3,
      clue: 'Große Augen, Stehenbleiben: Das kam völlig unerwartet. Die Freude kommt gleich danach.', signs: ['koerper', 'worte'] },
    { id: 'dc11', who: 'Inês', text: 'Inês wartet seit Stunden auf eine Antwort im Chat. Da steht nur: gelesen.', say: 'Egal. Ist mir doch egal.', body: 'Sie schaut alle zwei Minuten aufs Handy.',
      answer: 'Unsicherheit', options: ['Unsicherheit', 'Freude', 'Stolz', 'Ekel'], intensity: 2,
      clue: 'Sie sagt „egal“, schaut aber ständig nach. Das Verhalten verrät mehr als die Worte.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc12', who: 'Lara', text: 'Lara hat drei Wochen an einem Skate-Trick geübt. Heute klappt er zum ersten Mal.', say: 'Habt ihr das gesehen?!', body: 'Sie reißt beide Arme hoch.',
      answer: 'Stolz', options: ['Stolz', 'Scham', 'Langeweile', 'Angst'], intensity: 3,
      clue: 'Arme hoch, und alle sollen hinschauen: Sie ist stolz auf ihre Leistung.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc13', who: 'Milan', text: 'Milan kippt aus Versehen Kaffee über die Blätter der Lehrerin.', say: 'Oh nein. Sorry, sorry, sorry!', body: 'Er wischt hektisch mit dem Ärmel herum.',
      answer: 'Schuldgefühl', options: ['Schuldgefühl', 'Scham', 'Stolz', 'Langeweile'], also: ['Scham'], intensity: 2,
      clue: 'Oft „sorry“ sagen und es schnell gutmachen wollen: Er fühlt sich schuldig.', signs: ['koerper', 'worte'] },
    { id: 'dc14', who: 'Jana', text: 'Jana sitzt in der Pause allein auf der Bank. Ihre Freundinnen sind krank.', body: 'Sie scrollt durchs Handy, ohne richtig hinzuschauen.',
      answer: 'Einsamkeit', options: ['Einsamkeit', 'Langeweile', 'Wut', 'Stolz'], also: ['Langeweile'], intensity: 1,
      clue: 'Allein sein und ziellos scrollen. Es ist eher leise, also leichte Einsamkeit.', signs: ['koerper', 'situation'] },
    { id: 'dc15', who: 'Rui', text: 'Rui fährt zum ersten Mal allein mit dem Zug zur Gare.', say: 'Und wenn ich in den falschen Zug steige?', body: 'Er prüft zum fünften Mal die Fahrplan-App.',
      answer: 'Nervosität', options: ['Nervosität', 'Angst', 'Stolz', 'Ekel'], also: ['Angst'], intensity: 2,
      clue: 'Immer wieder prüfen und „was wenn“ fragen: typisch Nervosität. Etwas Neues steht an.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc16', who: 'Amira', text: 'Im Kochatelier ist Amiras Kuchen als Erstes aufgegessen.', say: 'Hab ich doch gesagt, der ist gut!', body: 'Sie strahlt und verschränkt lässig die Arme.',
      answer: 'Stolz', options: ['Stolz', 'Neid', 'Scham', 'Angst'], intensity: 2,
      clue: 'Strahlen und „hab ich doch gesagt“: Sie ist stolz. Lässig heißt: nicht übertrieben, also mittel.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc17', who: 'Kevin', text: 'Kevin will beim Fußball mitspielen. Einer sagt: „Wir sind schon voll.“ Dabei fehlt noch jemand.', say: 'Dann halt nicht.', body: 'Er dreht sich schnell weg und steckt die Hände in die Taschen.',
      answer: 'Enttäuschung', options: ['Enttäuschung', 'Wut', 'Freude', 'Ekel'], also: ['Wut'], intensity: 2,
      clue: 'Schnell wegdrehen und „dann halt nicht“: Er ist verletzt. Er zeigt es nur nicht offen.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc18', who: 'Nora', text: 'Nora lässt ihr Handy fallen. Das Display ist komplett gesplittert.', say: 'Nein, nein, nein. Bitte nicht.', body: 'Sie hält es mit beiden Händen und starrt drauf.',
      answer: 'Schreck', options: ['Schreck', 'Langeweile', 'Stolz', 'Vorfreude'], intensity: 3,
      clue: 'Erstarren und „nein, nein, nein“: Der Schreck sitzt tief. Ärger kommt oft erst danach.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc19', who: 'Elias', text: 'Elias rechnet dieselbe Mathe-Aufgabe zum vierten Mal. Wieder falsch.', say: 'Ich check das nie! Nie!', body: 'Er schiebt das Heft weg und lehnt sich zurück.',
      answer: 'Frust', options: ['Frust', 'Wut', 'Freude', 'Erleichterung'], also: ['Wut'], intensity: 2,
      clue: 'Es klappt immer wieder nicht. Heft wegschieben heißt: Er hat genug. Das ist Frust.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc20', who: 'Lena', text: 'Lenas beste Freundin hängt jetzt ständig mit Sara ab.', say: 'Aha. Schön für euch.', body: 'Sie schaut weg. Ihre Stimme wird kühl.',
      answer: 'Eifersucht', options: ['Eifersucht', 'Freude', 'Ekel', 'Langeweile'], intensity: 2,
      clue: 'Kühle Stimme und „schön für euch“: Sie hat Angst, ihre Freundin zu verlieren.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc21', who: 'Tiago', text: 'Tiago hat im Streit seinen Kumpel beleidigt. Jetzt redet der nicht mehr mit ihm.', say: 'Ich hab das nicht so gemeint …', body: 'Er tippt eine Nachricht und löscht sie wieder.',
      answer: 'Schuldgefühl', options: ['Schuldgefühl', 'Stolz', 'Freude', 'Ekel'], intensity: 2,
      clue: 'Er will es wiedergutmachen, traut sich aber noch nicht. Das zeigt ein Schuldgefühl.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc22', who: 'Aylin', text: 'Aylin gewinnt das Kicker-Turnier im Foyer. Gegen zwei Lehrer!', say: 'Revanche? Jederzeit!', body: 'Sie tanzt einmal um den Tisch.',
      answer: 'Freude', options: ['Freude', 'Scham', 'Angst', 'Ekel'], intensity: 3,
      clue: 'Tanzen und Sprüche klopfen: pure Freude. Ein bisschen Stolz ist sicher auch dabei.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc23', who: 'Jeff', text: 'Jeff steht an der Kasse. Sein Geld reicht nicht für alles.', say: 'Äh … dann lass ich die Cola weg.', body: 'Er lacht kurz und wird rot.',
      answer: 'Verlegenheit', options: ['Verlegenheit', 'Stolz', 'Wut', 'Vorfreude'], intensity: 2, heikel: true,
      clue: 'Kurzes Lachen und rot werden: Die Situation ist ihm unangenehm. Er bleibt aber cool.', signs: ['koerper', 'situation'] },
    { id: 'dc24', who: 'Noah', text: 'Noahs Lieblingsserie ist vorbei. Die allerletzte Folge ist gelaufen.', say: 'Und was mach ich jetzt mit meinem Leben?', body: 'Er grinst dabei ein bisschen.',
      answer: 'Trauer', options: ['Trauer', 'Wut', 'Ekel', 'Angst'], intensity: 1,
      clue: 'Er übertreibt mit Humor. Ein bisschen traurig ist er trotzdem. Also: leicht.', signs: ['koerper', 'worte'] },
    { id: 'dc25', who: 'Sara', text: 'Sara hat ihre Hausaufgaben vergessen. Die Lehrerin sagt: „Heute ist das okay.“', say: 'Puh. Danke!', body: 'Ihre Schultern sinken nach unten.',
      answer: 'Erleichterung', options: ['Erleichterung', 'Wut', 'Neid', 'Ekel'], intensity: 2,
      clue: '„Puh“ und lockere Schultern: Die Anspannung ist weg. Das ist Erleichterung.', signs: ['koerper', 'worte'] },
    { id: 'dc26', who: 'Luca', text: 'Lucas Kumpel darf beim Turnier spielen. Luca muss auf die Bank.', say: 'Klar. Der Trainer mag ihn halt.', body: 'Er verdreht die Augen.',
      answer: 'Neid', options: ['Neid', 'Freude', 'Scham', 'Angst'], intensity: 2,
      clue: 'Luca will das haben, was der andere hat. Augenrollen und Spruch zeigen Neid.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc27', who: 'Emir', text: 'Die Stunde dauert noch 40 Minuten. Emir schaut zur Uhr.', say: 'Ist die Uhr kaputt oder was?', body: 'Er malt Kreise ins Heft und gähnt.',
      answer: 'Langeweile', options: ['Langeweile', 'Angst', 'Stolz', 'Ekel'], intensity: 2,
      clue: 'Gähnen und Kritzeln: Der Kopf hat nichts zu tun. Klassische Langeweile.', signs: ['koerper', 'worte'] },
    { id: 'dc28', who: 'Yara', text: 'Yara hört nachts ein lautes Geräusch im Flur.', say: 'Hallo? … Ist da wer?', body: 'Sie zieht die Decke bis zur Nase.',
      answer: 'Angst', options: ['Angst', 'Freude', 'Langeweile', 'Stolz'], intensity: 2,
      clue: 'Leise fragen und sich verstecken: Das ist Angst. Der Körper sucht Schutz.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc29', who: 'Dylan', text: 'Dylans Chef im Praktikum lobt ihn vor allen anderen.', say: 'Ach, war nichts Besonderes.', body: 'Er lächelt und kratzt sich am Kopf.',
      answer: 'Stolz', options: ['Stolz', 'Verlegenheit', 'Wut', 'Ekel'], also: ['Verlegenheit'], intensity: 2,
      clue: 'Er spielt es runter, lächelt aber. Innen ist er stolz. Lob annehmen ist nicht leicht.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc30', who: 'Inês', text: 'Inês und ihre Freundin vertragen sich. Nach einer Woche Streit.', say: 'Ich hab dich echt vermisst.', body: 'Sie umarmt ihre Freundin lange.',
      answer: 'Freude', options: ['Freude', 'Erleichterung', 'Ekel', 'Wut'], also: ['Erleichterung'], intensity: 3,
      clue: 'Lange Umarmung, ehrliche Worte: große Freude. Erleichterung ist auch dabei.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc31', who: 'Lara', text: 'Jemand hat Laras Zeichnung im Flur mit dickem Stift bekritzelt.', say: 'Wer war das?!', body: 'Sie ballt die Fäuste. Ihre Stimme wird laut.',
      answer: 'Wut', options: ['Wut', 'Freude', 'Langeweile', 'Scham'], intensity: 3,
      clue: 'Fäuste und laute Stimme: starke Wut. Jemand hat etwas kaputt gemacht, das ihr wichtig ist.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc32', who: 'Milan', text: 'Milan soll im Schwimmbad vom Drei-Meter-Brett springen. Zum ersten Mal.', say: 'Ich schau erst mal den anderen zu.', body: 'Er stellt sich ganz hinten in die Schlange.',
      answer: 'Angst', options: ['Angst', 'Ekel', 'Stolz', 'Langeweile'], intensity: 2,
      clue: 'Er schiebt es raus und bleibt hinten. So zeigt sich Angst oft: ganz leise.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc33', who: 'Jana', text: 'Die Klasse fährt für zwei Tage nach Echternach. Jana darf mit.', say: 'Wann geht’s los? Bitte morgen!', body: 'Sie trommelt mit den Händen auf den Tisch.',
      answer: 'Vorfreude', options: ['Vorfreude', 'Trauer', 'Ekel', 'Scham'], intensity: 3,
      clue: 'Trommeln und „bitte morgen“: Sie kann es kaum erwarten. Das ist Vorfreude.', signs: ['koerper', 'worte'] },
    { id: 'dc34', who: 'Rui', text: 'Rui erzählt einen Witz. Niemand lacht. Es ist ganz still.', say: 'Okay … war wohl nix.', body: 'Er lacht kurz allein und schaut zur Seite.',
      answer: 'Verlegenheit', options: ['Verlegenheit', 'Stolz', 'Wut', 'Vorfreude'], intensity: 1,
      clue: 'Kurzes Lachen, Blick zur Seite: Es ist ihm etwas peinlich. Aber nur ein bisschen.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc35', who: 'Amira', text: 'Amira bekommt eine Nachricht: Sie hat den Praktikumsplatz in der Werkstatt!', say: 'Ich hab ihn! Ich hab den Platz!', body: 'Sie springt auf und zeigt allen das Handy.',
      answer: 'Freude', options: ['Freude', 'Angst', 'Neid', 'Langeweile'], intensity: 3,
      clue: 'Aufspringen und es allen zeigen: große Freude. Sie hat etwas Wichtiges erreicht.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc36', who: 'Kevin', text: 'Die Lehrerin sagt vor allen: „Kevin, schon wieder zu spät?“', say: 'Ja, ja. Der Bus halt.', body: 'Er setzt sich schnell und zieht die Kapuze hoch.',
      answer: 'Scham', options: ['Scham', 'Ärger', 'Freude', 'Stolz'], also: ['Ärger'], intensity: 2,
      clue: 'Vor allen angesprochen werden ist unangenehm. Kapuze hoch heißt: Er will unsichtbar sein.', signs: ['koerper', 'situation'] },
    { id: 'dc37', who: 'Nora', text: 'Nora sieht, wie ein Junge einem Kleineren die Mütze wegnimmt.', say: 'Hey! Gib die sofort zurück!', body: 'Sie geht schnell hin. Ihr Blick ist hart.',
      answer: 'Wut', options: ['Wut', 'Freude', 'Langeweile', 'Ekel'], intensity: 2,
      clue: 'Unfair zu Schwächeren: Das macht wütend. Ihre Wut hilft hier sogar jemandem.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc38', who: 'Elias', text: 'Elias probiert im Kochatelier zum ersten Mal Kachkéis.', say: 'Ähm … interessant.', body: 'Er schluckt langsam und greift sofort zum Wasser.',
      answer: 'Ekel', options: ['Ekel', 'Freude', 'Stolz', 'Angst'], intensity: 1,
      clue: 'Er bleibt höflich. Aber der Griff zum Wasser verrät ihn: leichter Ekel.', signs: ['koerper', 'worte'] },
    { id: 'dc39', who: 'Milan', text: 'Milans Kumpel schreibt ihm: „Wir müssen reden.“ Sonst nichts.', say: 'Hä? Was hab ich gemacht?', body: 'Er wippt mit dem Fuß und liest die Nachricht immer wieder.',
      answer: 'Nervosität', options: ['Nervosität', 'Freude', 'Ekel', 'Langeweile'], intensity: 2,
      clue: 'Wippen und immer wieder lesen: Er weiß nicht, was kommt. Das macht nervös.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc40', who: 'Dylan', text: 'Dylan verliert im Handyspiel zum 50. Mal dasselbe Level.', say: 'Dieses Spiel ist sowas von unfair!', body: 'Er wirft das Handy aufs Sofa.',
      answer: 'Frust', options: ['Frust', 'Freude', 'Scham', 'Angst'], intensity: 3,
      clue: 'Immer wieder scheitern, dann das Handy werfen: starker Frust.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc41', who: 'Yara', text: 'Yara ist neu in der Klasse. Alle anderen kennen sich schon.', say: 'Ähm … ist hier noch frei?', body: 'Sie spricht sehr leise und hält ihre Tasche fest.',
      answer: 'Unsicherheit', options: ['Unsicherheit', 'Wut', 'Stolz', 'Ekel'], intensity: 2,
      clue: 'Leise Stimme, Tasche festhalten: Sie weiß noch nicht, ob sie willkommen ist.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc42', who: 'Jana', text: 'Vor dem Supermarkt ist ein Hund angebunden. Es regnet stark.', say: 'Du Armer, du bist ja ganz nass.', body: 'Jana geht in die Hocke und hält ihm die Hand hin.',
      answer: 'Mitgefühl', options: ['Mitgefühl', 'Ekel', 'Stolz', 'Langeweile'], intensity: 2,
      clue: 'Sie spürt, wie es dem Hund geht, und will helfen. Das ist Mitgefühl.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc43', who: 'Emir', text: 'Emir bekommt von seiner Oma genau das Spiel, das er sich gewünscht hat.', say: 'Oma, woher wusstest du das?', body: 'Er drückt das Spiel an sich und umarmt sie.',
      answer: 'Dankbarkeit', options: ['Dankbarkeit', 'Ekel', 'Angst', 'Langeweile'], intensity: 3,
      clue: 'Umarmung und Staunen: Er freut sich und ist dankbar. Jemand hat an ihn gedacht.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc44', who: 'Sara', text: 'Sara merkt: Sie hat zwei Stunden für die falsche Prüfung gelernt.', say: 'Das ist jetzt ein Witz, oder?', body: 'Sie lacht, aber es klingt verzweifelt.',
      answer: 'Frust', options: ['Frust', 'Überraschung', 'Stolz', 'Langeweile'], also: ['Überraschung'], intensity: 3,
      clue: 'Viel Mühe für nichts: Das frustriert. Das Lachen ist nicht fröhlich, sondern verzweifelt.', signs: ['worte', 'situation'] },
    { id: 'dc45', who: 'Kevin', text: 'Kevin sieht Fotos von einer Party. Fast die ganze Klasse war da, nur er nicht.', body: 'Er legt das Handy weg und bleibt lange liegen.',
      answer: 'Einsamkeit', options: ['Einsamkeit', 'Freude', 'Ekel', 'Stolz'], intensity: 3,
      clue: 'Nicht eingeladen sein tut weh. Lange liegen bleiben zeigt: Das Gefühl ist stark.', signs: ['koerper', 'situation'] },
    { id: 'dc46', who: 'Luca', text: 'Luca soll im Praktikum zum ersten Mal allein die Kasse machen.', say: 'Okay. Ich schaff das. Glaub ich.', body: 'Er atmet tief durch und richtet sich auf.',
      answer: 'Nervosität', options: ['Nervosität', 'Ekel', 'Langeweile', 'Trauer'], intensity: 1,
      clue: 'Tief durchatmen und sich Mut machen: etwas nervös, aber er hat es im Griff.', signs: ['koerper', 'worte', 'situation'] },
    // Kleine Alltagsmomente (eher leichte Gefühle)
    { id: 'dc47', who: 'Mia', text: 'Jemand hat Mias Lieblingsplatz im Bus genommen. Sie setzt sich woanders hin.', say: 'Na super. Danke auch.', body: 'Sie rollt kurz mit den Augen und setzt die Kopfhörer auf.',
      answer: 'Ärger', options: ['Ärger', 'Angst', 'Freude', 'Scham'], intensity: 1,
      clue: 'Augenrollen und ein Spruch: Sie ist genervt. Aber sie regt sich nicht lange auf. Also leicht.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc48', who: 'Noah', text: 'Noah findet in seiner Jacke noch einen Müsliriegel.', say: 'Ey, nice. Frühstück gerettet.', body: 'Er grinst kurz und isst ihn im Gehen.',
      answer: 'Freude', options: ['Freude', 'Wut', 'Scham', 'Angst'], intensity: 1,
      clue: 'Kurzes Grinsen, dann geht der Tag weiter: eine kleine Freude. Also leicht.', signs: ['koerper', 'worte'] },
    { id: 'dc49', who: 'Lara', text: 'Lara wollte in der Pause Pommes kaufen. Heute gibt es keine.', say: 'Schade. Dann halt Nudeln.', body: 'Sie zuckt mit den Schultern.',
      answer: 'Enttäuschung', options: ['Enttäuschung', 'Wut', 'Angst', 'Stolz'], intensity: 1,
      clue: 'Schulterzucken und „schade“: Sie ist kurz enttäuscht. Aber schnell wieder okay.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc50', who: 'Elias', text: 'Elias ist zum ersten Mal im neuen Gebäude. Er findet den Raum nicht.', say: 'Äh, sorry … wo ist Raum 12?', body: 'Er spricht leise, lächelt aber dabei.',
      answer: 'Unsicherheit', options: ['Unsicherheit', 'Wut', 'Ekel', 'Stolz'], intensity: 1,
      clue: 'Leise fragen, aber lächeln: Er ist etwas unsicher. Nur ein bisschen.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc51', who: 'Nora', text: 'Nora hat ihr Fahrrad selbst repariert. Der Reifen hält.', say: 'Geht doch.', body: 'Sie nickt kurz und wischt sich die Hände ab.',
      answer: 'Stolz', options: ['Stolz', 'Trauer', 'Angst', 'Ekel'], intensity: 1,
      clue: '„Geht doch“ und ein kurzes Nicken: Sie ist zufrieden mit sich. Leiser Stolz.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc52', who: 'Inês', text: 'Inês bekommt im Bus eine Nachricht von einer alten Freundin.', say: 'Oh, die gibt’s ja auch noch!', body: 'Sie hebt die Augenbrauen und lächelt.',
      answer: 'Überraschung', options: ['Überraschung', 'Wut', 'Ekel', 'Scham'], intensity: 1,
      clue: 'Augenbrauen hoch: Das kam unerwartet. Aber ganz entspannt, also leicht.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc53', who: 'Amira', text: 'Amira stolpert im Flur fast über ihre Tasche. Keiner hat es gesehen.', say: 'Hoppla. Zum Glück guckt keiner.', body: 'Sie schaut sich schnell um und lacht leise.',
      answer: 'Verlegenheit', options: ['Verlegenheit', 'Wut', 'Trauer', 'Stolz'], intensity: 1,
      clue: 'Schnell umschauen, leise lachen: ein kleiner peinlicher Moment. Nichts Großes.', signs: ['koerper', 'worte', 'situation'] },

    // Heikel (nur mit Freigabe der Lehrkraft)
    { id: 'dc60', who: 'Tiago', text: 'Tiagos Eltern streiten laut in der Küche. Er sitzt in seinem Zimmer.', body: 'Er macht die Musik lauter und starrt an die Decke.',
      answer: 'Sorge', options: ['Sorge', 'Freude', 'Langeweile', 'Stolz'], intensity: 2, heikel: true,
      clue: 'Musik lauter heißt: Er will es nicht hören. Streit zu Hause macht vielen Sorgen.', signs: ['koerper', 'situation'] },
    { id: 'dc61', who: 'Lena', text: 'Lenas Katze ist gestern gestorben. In der Schule fragt jemand: „Alles okay?“', say: 'Ja. Geht schon.', body: 'Ihre Augen sind rot. Sie spricht sehr leise.',
      answer: 'Trauer', options: ['Trauer', 'Wut', 'Langeweile', 'Stolz'], intensity: 3, heikel: true,
      clue: 'Rote Augen, leise Stimme: große Trauer. „Geht schon“ heißt hier: Ich will nicht reden.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc62', who: 'Aylin', text: 'Jemand kommentiert Aylins neue Frisur nur mit: „Mutig.“', say: 'Wie meinst du das?', body: 'Sie fasst sich an die Haare und checkt die Handykamera.',
      answer: 'Unsicherheit', options: ['Unsicherheit', 'Freude', 'Langeweile', 'Ekel'], intensity: 2, heikel: true,
      clue: 'Haare anfassen, Kamera checken: Sie zweifelt plötzlich an sich. Ein Wort kann viel auslösen.', signs: ['koerper', 'worte', 'situation'] },
    { id: 'dc63', who: 'Rui', text: 'Jemand fragt Rui zum dritten Mal: „Und woher kommst du wirklich?“', say: 'Aus Esch. Wie schon gesagt.', body: 'Er atmet tief ein und verdreht kurz die Augen.',
      answer: 'Ärger', options: ['Ärger', 'Freude', 'Angst', 'Ekel'], intensity: 2, heikel: true,
      clue: 'Zum dritten Mal dieselbe Frage nervt. Er bleibt ruhig, aber genervt ist er schon.', signs: ['koerper', 'worte', 'situation'] },
  ];
})();
