// Französische Kurzbezeichnungen der ELDiB-Ziele für die Lehrerseite der
// französischen Arbeitsblätter – übernommen aus dem ELDiB-Generator des CDSE
// (dieselben Stichwörter wie dort, damit Hub, Generator und Toolbox einheitlich sind).
export const ELDIB_FR: Record<string, string> = {
  // V
  'V-1': "Perception", 'V-2': "Orientation", 'V-3': "Attention", 'V-4': "Réaction motrice",
  'V-5': "Réaction complexe", 'V-6': "Autonomie", 'V-7': "Matériel de jeu", 'V-8': "Routine",
  'V-9': "Expérience de jeu", 'V-10': "Attendre", 'V-11': "Rester assis", 'V-12': "Activité physique",
  'V-13': "Activités", 'V-14': "Félicitations / Succès", 'V-15': "Terminer", 'V-16': "Attentes",
  'V-17': "Raisons", 'V-18': "Alternatives", 'V-19': "Sélection dans un groupe", 'V-20': "Retenir",
  'V-21': "Contrôle de soi", 'V-22': "Progrès", 'V-23': "Flexibilité", 'V-24': "Nouvelles expériences",
  'V-25': "Application", 'V-26': "Provocation", 'V-27': "Responsabilité", 'V-28': "Proposition",
  'V-29': "Habitudes", 'V-30': "Rôle positif", 'V-31': "Droit/Règlements", 'V-32': "Autodétermination",
  'V-33': "Résolution",
  // K
  'K-1': "Sons", 'K-2': "Orateur", 'K-3': "Stimulus verbal", 'K-4': "Approximation de mots",
  'K-5': "Mots spontanés", 'K-6': "Mots – adulte", 'K-7': "Mots – pairs", 'K-8': "Ordre des mots",
  'K-9': "Réponse", 'K-10': "Vocabulaire", 'K-11': "Séquences de mots", 'K-12': "Échange – adultes",
  'K-13': "Caractéristiques", 'K-14': "Échange – Enfant", 'K-15': "Informations personnelles", 'K-16': "Réactions émotionnelles",
  'K-17': "Discussions", 'K-18': "Fierté – moi", 'K-19': "Attributs – moi", 'K-20': "Attributs – vous",
  'K-21': "Sentiments – vous", 'K-22': "Fierté – nous", 'K-23': "Créativité", 'K-24': "Progrès",
  'K-25': "Influence", 'K-26': "Sentiments – moi", 'K-27': "Relation", 'K-28': "Soutien",
  'K-29': "Rapports logiques", 'K-30': "Énoncés complexes", 'K-31': "Médiation", 'K-32': "Reconnaissance",
  'K-33': "Motifs", 'K-34': "Idéaux", 'K-35': "Maintien/entretien",
  // SOZ
  'SOZ-1': "Présence", 'SOZ-2': "Attention dirigée", 'SOZ-3': "Nom propre", 'SOZ-4': "Jeu seul",
  'SOZ-5': "Interaction non verbale", 'SOZ-6': "Venir", 'SOZ-7': "Demandes", 'SOZ-8': "Mots – adulte",
  'SOZ-9': "Conscience de soi", 'SOZ-10': "Jeu parallèle", 'SOZ-11': "Mots – pairs", 'SOZ-12': "Recherche de contact",
  'SOZ-13': "Imagination", 'SOZ-14': "Attendre", 'SOZ-15': "Contact", 'SOZ-16': "Partager",
  'SOZ-17': "Jeu interactif", 'SOZ-18': "Coopération", 'SOZ-19': "Alternance", 'SOZ-20': "Imitation",
  'SOZ-21': "Évaluation", 'SOZ-22': "Démonstration", 'SOZ-23': "Propose – autre", 'SOZ-24': "Expériences",
  'SOZ-25': "Préférence", 'SOZ-26': "Soutien", 'SOZ-27': "Règles de groupe", 'SOZ-28': "Identification",
  'SOZ-29': "Expérience de groupe", 'SOZ-30': "Activité de groupe", 'SOZ-31': "Différence", 'SOZ-32': "Respect",
  'SOZ-33': "Intérêt", 'SOZ-34': "Proposition", 'SOZ-35': "Valeurs", 'SOZ-36': "Conclusions",
  'SOZ-37': "Empathie", 'SOZ-38': "Différents rôles", 'SOZ-39': "Principes", 'SOZ-40': "Perception de soi",
  'SOZ-41': "Relations interpersonnelles",
  // KOG
  'KOG-1': "Orientation", 'KOG-2': "Attention", 'KOG-3': "Mémoire à court terme", 'KOG-4': "Réaction complexe",
  'KOG-5': "Imitation simple", 'KOG-6': "Habiletés motrices – 18 mois", 'KOG-7': "Désignation", 'KOG-8': "Approximation de mots",
  'KOG-9': "Mots spontanés", 'KOG-10': "Forme", 'KOG-11': "Parties du corps", 'KOG-12': "Détails",
  'KOG-13': "Trier", 'KOG-14': "Nommer des images", 'KOG-15': "Valeur utilitaire", 'KOG-16': "Corps – 3",
  'KOG-17': "Série identique", 'KOG-18': "Motricité fine – 3", 'KOG-19': "Série – différente", 'KOG-20': "Opposés",
  'KOG-21': "Catégoriser", 'KOG-22': "Compter – 4", 'KOG-23': "Couleurs", 'KOG-24': "Alternance",
  'KOG-25': "Compter – 10", 'KOG-26': "Œil – Main – 5", 'KOG-27': "Différencier", 'KOG-28': "Corps – 5",
  'KOG-29': "Objets – 5", 'KOG-30': "Mémoire", 'KOG-31': "Série d'images", 'KOG-32': "Œil – Main – 6",
  'KOG-33': "Corps – 6", 'KOG-34': "Lire – 50", 'KOG-35': "Nombres – 10", 'KOG-36': "Écrire – 50",
  'KOG-37': "Comprendre", 'KOG-38': "Expliquer", 'KOG-39': "Comprendre le sens", 'KOG-40': "Plus/moins – 9",
  'KOG-41': "Illogisme", 'KOG-42': "Répondre aux questions", 'KOG-43': "Jeux de sport", 'KOG-44': "Phrases libres",
  'KOG-45': "Concepts numériques", 'KOG-46': "Quantitatives", 'KOG-47': "Faits et circonstances", 'KOG-48': "Opérations",
  'KOG-49': "Communication", 'KOG-50': "Multiplication/Division – 100", 'KOG-51': "Recueil d'information", 'KOG-52': "Valeur monétaire – 10€",
  'KOG-53': "Fiction", 'KOG-54': "Grammaire", 'KOG-55': "Valeurs", 'KOG-56': "Concepts",
  'KOG-57': "Événements actuels", 'KOG-58': "Opinions", 'KOG-59': "Incohérence", 'KOG-60': "Problèmes mathématiques",
  'KOG-61': "Résolution", 'KOG-62': "Citoyenneté",
}
