// ---------------------------------------------------------------------------
// Geprüfte Quellen für die Seite „Für die Lehrperson“. Blätter dürfen nur
// Quellen aus dieser Liste nennen (das Prüfskript kontrolliert das) – so
// taucht nie eine erfundene Literaturangabe auf.
// ---------------------------------------------------------------------------

export const QUELLEN: Record<string, string> = {
  // Emotionen & Emotionsregulation
  gross1998: 'Gross, J. J. (1998). The emerging field of emotion regulation: An integrative review. Review of General Psychology, 2(3), 271–299.',
  petermannWiedebusch2016: 'Petermann, F. & Wiedebusch, S. (2016). Emotionale Kompetenz bei Kindern (3. Aufl.). Göttingen: Hogrefe.',
  saarni1999: 'Saarni, C. (1999). The Development of Emotional Competence. New York: Guilford.',
  denham1998: 'Denham, S. A. (1998). Emotional Development in Young Children. New York: Guilford.',
  gottman1997: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child. New York: Simon & Schuster.',
  brackett2019: 'Brackett, M. A. (2019). Permission to Feel. New York: Celadon.',
  siegelBryson2011: 'Siegel, D. J. & Bryson, T. P. (2011). The Whole-Brain Child. New York: Delacorte.',
  linehan2015: 'Linehan, M. M. (2015). DBT Skills Training Manual (2nd ed.). New York: Guilford.',
  rathusMiller2015: 'Rathus, J. H. & Miller, A. L. (2015). DBT Skills Manual for Adolescents. New York: Guilford.',
  kabatZinn1990: 'Kabat-Zinn, J. (1990). Full Catastrophe Living. New York: Delacorte.',
  kendallHedtke2006: 'Kendall, P. C. & Hedtke, K. A. (2006). Cognitive-Behavioral Therapy for Anxious Children: Therapist Manual (3rd ed.). Ardmore, PA: Workbook Publishing.',
  rapee2008: 'Rapee, R. M., Wignall, A., Spence, S. H., Cobham, V. & Lyneham, H. (2008). Helping Your Anxious Child (2nd ed.). Oakland: New Harbinger.',
  zeidner1998: 'Zeidner, M. (1998). Test Anxiety: The State of the Art. New York: Plenum.',
  goleman1995: 'Goleman, D. (1995). Emotional Intelligence. New York: Bantam.',

  // Kognitive Verhaltenstherapie & Selbststeuerung
  ellis1962: 'Ellis, A. (1962). Reason and Emotion in Psychotherapy. New York: Lyle Stuart.',
  beck2011: 'Beck, J. S. (2011). Cognitive Behavior Therapy: Basics and Beyond (2nd ed.). New York: Guilford.',
  meichenbaumGoodman1971: 'Meichenbaum, D. & Goodman, J. (1971). Training impulsive children to talk to themselves. Journal of Abnormal Psychology, 77(2), 115–126.',
  robin1976: 'Robin, A., Schneider, M. & Dolnick, M. (1976). The turtle technique: An extended case study of self-control in the classroom. Psychology in the Schools, 13(4), 449–453.',
  kanfer2012: 'Kanfer, F. H., Reinecker, H. & Schmelzer, D. (2012). Selbstmanagement-Therapie (5. Aufl.). Berlin: Springer.',
  mischel2014: 'Mischel, W. (2014). The Marshmallow Test. New York: Little, Brown.',
  diamond2013: 'Diamond, A. (2013). Executive functions. Annual Review of Psychology, 64, 135–168.',
  barkley2012: 'Barkley, R. A. (2012). Executive Functions: What They Are, How They Work, and Why They Evolved. New York: Guilford.',
  bandura1977: 'Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change. Psychological Review, 84(2), 191–215.',

  // Verhalten, Verstärkung, Schule
  petermann2012: 'Petermann, F. & Petermann, U. (2012). Training mit aggressiven Kindern (13. Aufl.). Weinheim: Beltz.',
  doepfner2019: 'Döpfner, M., Schürmann, S. & Frölich, J. (2019). Therapieprogramm für Kinder mit hyperkinetischem und oppositionellem Problemverhalten THOP (6. Aufl.). Weinheim: Beltz.',
  crone2010: 'Crone, D. A., Hawken, L. S. & Horner, R. H. (2010). Responding to Problem Behavior in Schools: The Behavior Education Program (2nd ed.). New York: Guilford.',
  kazdin2008: 'Kazdin, A. E. (2008). The Kazdin Method for Parenting the Defiant Child. Boston: Houghton Mifflin.',
  premack1959: 'Premack, D. (1959). Toward empirical behavior laws: I. Positive reinforcement. Psychological Review, 66(4), 219–233.',
  nolting2002: 'Nolting, H.-P. (2002). Störungen in der Schulklasse. Weinheim: Beltz.',
  omer2004: 'Omer, H. & von Schlippe, A. (2004). Autorität durch Beziehung. Göttingen: Vandenhoeck & Ruprecht.',
  zehr2002: 'Zehr, H. (2002). The Little Book of Restorative Justice. Intercourse, PA: Good Books.',
  wachtel2016: 'Wachtel, T. (2016). Defining Restorative. Bethlehem, PA: International Institute for Restorative Practices.',
  wood1996: 'Wood, M. M. (1996). Developmental Therapy – Developmental Teaching (3rd ed.). Austin: Pro-Ed.',
  bergsson1998: 'Bergsson, M. & Luckfiel, H. (1998). Umgang mit „schwierigen“ Kindern. Berlin: Cornelsen Scriptor.',

  // Soziales Lernen, Konflikte, Mobbing
  durlak2011: 'Durlak, J. A., Weissberg, R. P., Dymnicki, A. B., Taylor, R. D. & Schellinger, K. B. (2011). The impact of enhancing students’ social and emotional learning: A meta-analysis of school-based universal interventions. Child Development, 82(1), 405–432.',
  greenberg1995: 'Greenberg, M. T., Kusché, C. A., Cook, E. T. & Quamma, J. P. (1995). Promoting emotional competence in school-aged children: The effects of the PATHS curriculum. Development and Psychopathology, 7(1), 117–136.',
  websterStratton2003: 'Webster-Stratton, C. & Reid, M. J. (2003). Treating conduct problems and strengthening social and emotional competence in young children: The Dina Dinosaur treatment program. Journal of Emotional and Behavioral Disorders, 11(3), 130–143.',
  shure1992: 'Shure, M. B. (1992). I Can Problem Solve (ICPS). Champaign, IL: Research Press.',
  cierpka2005: 'Cierpka, M. (Hrsg.) (2005). Faustlos – Wie Kinder Konflikte gewaltfrei lösen lernen. Freiburg: Herder.',
  rosenberg2001: 'Rosenberg, M. B. (2001). Gewaltfreie Kommunikation. Paderborn: Junfermann.',
  gordon1972: 'Gordon, T. (1972). Familienkonferenz. Hamburg: Hoffmann und Campe.',
  fisherUry1981: 'Fisher, R. & Ury, W. (1981). Getting to Yes. Boston: Houghton Mifflin.',
  olweus1993: 'Olweus, D. (1993). Bullying at School: What We Know and What We Can Do. Oxford: Blackwell.',
  salmivalli1996: 'Salmivalli, C., Lagerspetz, K., Björkqvist, K., Österman, K. & Kaukiainen, A. (1996). Bullying as a group process: Participant roles and their relations to social status within the group. Aggressive Behavior, 22(1), 1–15.',
  gray2015: 'Gray, C. (2015). The New Social Story Book. Arlington, TX: Future Horizons.',

  // Stärken, Resilienz, Motivation
  masten2014: 'Masten, A. S. (2014). Ordinary Magic: Resilience in Development. New York: Guilford.',
  wernerSmith1992: 'Werner, E. E. & Smith, R. S. (1992). Overcoming the Odds. Ithaca: Cornell University Press.',
  antonovsky1987: 'Antonovsky, A. (1987). Unraveling the Mystery of Health. San Francisco: Jossey-Bass.',
  petersonSeligman2004: 'Peterson, C. & Seligman, M. E. P. (2004). Character Strengths and Virtues. New York: Oxford University Press.',
  seligman2005: 'Seligman, M. E. P., Steen, T. A., Park, N. & Peterson, C. (2005). Positive psychology progress: Empirical validation of interventions. American Psychologist, 60(5), 410–421.',
  deciRyan2000: 'Deci, E. L. & Ryan, R. M. (2000). The “what” and “why” of goal pursuits. Psychological Inquiry, 11(4), 227–268.',
  dweck2006: 'Dweck, C. S. (2006). Mindset: The New Psychology of Success. New York: Random House.',
  gollwitzer1999: 'Gollwitzer, P. M. (1999). Implementation intentions: Strong effects of simple plans. American Psychologist, 54(7), 493–503.',
  oettingen2014: 'Oettingen, G. (2014). Rethinking Positive Thinking. New York: Current.',
  millerRollnick2013: 'Miller, W. R. & Rollnick, S. (2013). Motivational Interviewing (3rd ed.). New York: Guilford.',
  deShazer1985: 'de Shazer, S. (1985). Keys to Solution in Brief Therapy. New York: Norton.',
  steinberg2014: 'Steinberg, L. (2014). Age of Opportunity: Lessons from the New Science of Adolescence. Boston: Houghton Mifflin Harcourt.',

  // Lernen & Organisation
  zimmerman2002: 'Zimmerman, B. J. (2002). Becoming a self-regulated learner: An overview. Theory Into Practice, 41(2), 64–70.',
  dunlosky2013: 'Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J. & Willingham, D. T. (2013). Improving students’ learning with effective learning techniques. Psychological Science in the Public Interest, 14(1), 4–58.',
  hattieTimperley2007: 'Hattie, J. & Timperley, H. (2007). The power of feedback. Review of Educational Research, 77(1), 81–112.',
  steel2007: 'Steel, P. (2007). The nature of procrastination: A meta-analytic and theoretical review of quintessential self-regulatory failure. Psychological Bulletin, 133(1), 65–94.',
  sirois2013: 'Sirois, F. & Pychyl, T. (2013). Procrastination and the priority of short-term mood regulation. Social and Personality Psychology Compass, 7(2), 115–127.',
  cirillo2018: 'Cirillo, F. (2018). The Pomodoro Technique. New York: Currency.',

  // Alltag, Gesundheit, Medien, Visualisierung
  paruthi2016: 'Paruthi, S. et al. (2016). Recommended amount of sleep for pediatric populations: A consensus statement of the American Academy of Sleep Medicine. Journal of Clinical Sleep Medicine, 12(6), 785–786.',
  who2019: 'World Health Organization (2019). Guidelines on physical activity, sedentary behaviour and sleep for children under 5 years of age. Genf: WHO.',
  livingstone2020: 'Livingstone, S. & Blum-Ross, A. (2020). Parenting for a Digital Future. New York: Oxford University Press.',
  beesecure: 'BEE SECURE – Initiative der luxemburgischen Regierung für ein sichereres Internet: www.bee-secure.lu',
  klicksafe: 'klicksafe – EU-Initiative für mehr Sicherheit im Netz: www.klicksafe.de',
  hodgdon1995: 'Hodgdon, L. A. (1995). Visual Strategies for Improving Communication. Troy, MI: QuirkRoberts.',
  mesibov2004: 'Mesibov, G. B., Shea, V. & Schopler, E. (2004). The TEACCH Approach to Autism Spectrum Disorders. New York: Springer.',
  stanleyBrown2012: 'Stanley, B. & Brown, G. K. (2012). Safety planning intervention: A brief intervention to mitigate suicide risk. Cognitive and Behavioral Practice, 19(2), 256–264.',
  rogers1951: 'Rogers, C. R. (1951). Client-Centered Therapy. Boston: Houghton Mifflin.',

  // Skills-Kurs: Gefühle, Körper, Achtsamkeit, Gesundheit
  willcox1982: 'Willcox, G. (1982). The Feeling Wheel: A tool for expanding awareness of emotions and increasing spontaneity and intimacy. Transactional Analysis Journal, 12(4), 274–276.',
  ekman1992: 'Ekman, P. (1992). An argument for basic emotions. Cognition and Emotion, 6(3–4), 169–200.',
  plutchik2001: 'Plutchik, R. (2001). The nature of emotions. American Scientist, 89(4), 344–350.',
  keltnerEkman2015: 'Keltner, D. & Ekman, P. (2015, 3. Juli). The science of “Inside Out”. The New York Times.',
  lieberman2007: 'Lieberman, M. D., Eisenberger, N. I., Crockett, M. J., Tom, S. M., Pfeifer, J. H. & Way, B. M. (2007). Putting feelings into words: Affect labeling disrupts amygdala activity in response to affective stimuli. Psychological Science, 18(5), 421–428.',
  nummenmaa2014: 'Nummenmaa, L., Glerean, E., Hari, R. & Hietanen, J. K. (2014). Bodily maps of emotions. Proceedings of the National Academy of Sciences, 111(2), 646–651.',
  larsen2001: 'Larsen, J. T., McGraw, A. P. & Cacioppo, J. T. (2001). Can people feel happy and sad at the same time? Journal of Personality and Social Psychology, 81(4), 684–696.',
  fredrickson2001: 'Fredrickson, B. L. (2001). The role of positive emotions in positive psychology: The broaden-and-build theory of positive emotions. American Psychologist, 56(3), 218–226.',
  fleischhaker2011: 'Fleischhaker, C., Sixt, B. & Schulz, E. (2011). DBT-A: Dialektisch-behaviorale Therapie für Jugendliche. Berlin: Springer.',
  jacobson1929: 'Jacobson, E. (1929). Progressive Relaxation. Chicago: University of Chicago Press.',
  zaccaro2018: 'Zaccaro, A., Piarulli, A., Laurino, M., Garbella, E., Menicucci, D., Neri, B. & Gemignani, A. (2018). How breath-control can change your life: A systematic review on psycho-physiological correlates of slow breathing. Frontiers in Human Neuroscience, 12, 353.',
  balban2023: 'Balban, M. Y., Neri, E., Kogon, M. M., Weed, L., Nouriani, B., Jo, B., Holl, G., Zeitzer, J. M., Spiegel, D. & Huberman, A. D. (2023). Brief structured respiration practices enhance mood and reduce physiological arousal. Cell Reports Medicine, 4(1), 100895.',
  zenner2014: 'Zenner, C., Herrnleben-Kurz, S. & Walach, H. (2014). Mindfulness-based interventions in schools – a systematic review and meta-analysis. Frontiers in Psychology, 5, 603.',
  hayes2012: 'Hayes, S. C., Strosahl, K. D. & Wilson, K. G. (2012). Acceptance and Commitment Therapy: The Process and Practice of Mindful Change (2nd ed.). New York: Guilford.',
  krossAyduk2017: 'Kross, E. & Ayduk, O. (2017). Self-distancing: Theory, research, and current directions. Advances in Experimental Social Psychology, 55, 81–136.',
  kaplan1995: 'Kaplan, S. (1995). The restorative benefits of nature: Toward an integrative framework. Journal of Environmental Psychology, 15(3), 169–182.',
  lazarusFolkman1984: 'Lazarus, R. S. & Folkman, S. (1984). Stress, Appraisal, and Coping. New York: Springer.',
  who2020: 'World Health Organization (2020). WHO Guidelines on Physical Activity and Sedentary Behaviour. Genf: WHO.',
  carskadon2011: 'Carskadon, M. A. (2011). Sleep in adolescents: The perfect storm. Pediatric Clinics of North America, 58(3), 637–647.',

  // Skills-Kurs: Ich, Stärken, Gedanken
  maslow1943: 'Maslow, A. H. (1943). A theory of human motivation. Psychological Review, 50(4), 370–396.',
  grawe2004: 'Grawe, K. (2004). Neuropsychotherapie. Göttingen: Hogrefe.',
  cain2012: 'Cain, S. (2012). Quiet: The Power of Introverts in a World That Can’t Stop Talking. New York: Crown.',
  luftIngham1955: 'Luft, J. & Ingham, H. (1955). The Johari window, a graphic model of interpersonal awareness. Proceedings of the Western Training Laboratory in Group Development. Los Angeles: University of California.',
  ncube2006: 'Ncube, N. (2006). The Tree of Life Project: Using narrative ideas in work with vulnerable children. International Journal of Narrative Therapy and Community Work, 1, 3–16.',
  harter2012: 'Harter, S. (2012). The Construction of the Self (2nd ed.). New York: Guilford.',
  neff2003: 'Neff, K. D. (2003). Self-compassion: An alternative conceptualization of a healthy attitude toward oneself. Self and Identity, 2(2), 85–101.',
  stallard2019: 'Stallard, P. (2019). Think Good, Feel Good: A Cognitive Behavioural Therapy Workbook for Children and Young People (2nd ed.). Chichester: Wiley.',
  emmonsMcCullough2003: 'Emmons, R. A. & McCullough, M. E. (2003). Counting blessings versus burdens: An experimental investigation of gratitude and subjective well-being in daily life. Journal of Personality and Social Psychology, 84(2), 377–389.',
  pennebaker1997: 'Pennebaker, J. W. (1997). Writing about emotional experiences as a therapeutic process. Psychological Science, 8(3), 162–166.',

  // Skills-Kurs: Gruppe, Kommunikation, Konflikte, Medien
  tuckman1965: 'Tuckman, B. W. (1965). Developmental sequence in small groups. Psychological Bulletin, 63(6), 384–399.',
  coe2012: 'Council of Europe (2012). Compass: Manual for Human Rights Education with Young People (2nd ed.). Strasbourg: Council of Europe Publishing.',
  watzlawick1967: 'Watzlawick, P., Beavin, J. H. & Jackson, D. D. (1967). Pragmatics of Human Communication. New York: Norton.',
  schulzVonThun1981: 'Schulz von Thun, F. (1981). Miteinander reden 1: Störungen und Klärungen. Reinbek: Rowohlt.',
  hall1966: 'Hall, E. T. (1966). The Hidden Dimension. Garden City, NY: Doubleday.',
  glasl1980: 'Glasl, F. (1980). Konfliktmanagement. Bern: Haupt.',
  thomasKilmann1974: 'Thomas, K. W. & Kilmann, R. H. (1974). Thomas-Kilmann Conflict Mode Instrument. Tuxedo, NY: Xicom.',
  asch1956: 'Asch, S. E. (1956). Studies of independence and conformity: I. A minority of one against a unanimous majority. Psychological Monographs: General and Applied, 70(9), 1–70.',
  gardnerSteinberg2005: 'Gardner, M. & Steinberg, L. (2005). Peer influence on risk taking, risk preference, and risky decision making in adolescence and adulthood: An experimental study. Developmental Psychology, 41(4), 625–635.',
  lataneDarley1970: 'Latané, B. & Darley, J. M. (1970). The Unresponsive Bystander: Why Doesn’t He Help? New York: Appleton-Century-Crofts.',
  kaerna2011: 'Kärnä, A., Voeten, M., Little, T. D., Poskiparta, E., Kaljonen, A. & Salmivalli, C. (2011). A large-scale evaluation of the KiVa antibullying program: Grades 4–6. Child Development, 82(1), 311–330.',
  hindujaPatchin2015: 'Hinduja, S. & Patchin, J. W. (2015). Bullying Beyond the Schoolyard (2nd ed.). Thousand Oaks, CA: Corwin.',
  orbenPrzybylski2019: 'Orben, A. & Przybylski, A. K. (2019). The association between adolescent well-being and digital technology use. Nature Human Behaviour, 3(2), 173–182.',
  fardouly2015: 'Fardouly, J., Diedrichs, P. C., Vartanian, L. R. & Halliwell, E. (2015). Social comparisons on social media: The impact of Facebook on young women’s body image concerns and mood. Body Image, 13, 38–45.',
  roozenbeek2019: 'Roozenbeek, J. & van der Linden, S. (2019). Fake news game confers psychological resistance against online misinformation. Palgrave Communications, 5, 65.',
  wineburgMcGrew2019: 'Wineburg, S. & McGrew, S. (2019). Lateral reading and the nature of expertise: Reading less and learning more when evaluating digital information. Teachers College Record, 121(11), 1–40.',
  allport1954: 'Allport, G. W. (1954). The Nature of Prejudice. Cambridge, MA: Addison-Wesley.',

  // Skills-Kurs, Jahr 2 und 3: Selbstwert, Schule, Wut, Beziehungen, Vielfalt, Netz, Gesundheit
  rosenberg1965: 'Rosenberg, M. (1965). Society and the Adolescent Self-Image. Princeton, NJ: Princeton University Press.',
  crockerWolfe2001: 'Crocker, J. & Wolfe, C. T. (2001). Contingencies of self-worth. Psychological Review, 108(3), 593–623.',
  roedigerKarpicke2006: 'Roediger, H. L. & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. Psychological Science, 17(3), 249–255.',
  cepeda2006: 'Cepeda, N. J., Pashler, H., Vul, E., Wixted, J. T. & Rohrer, D. (2006). Distributed practice in verbal recall tasks: A review and quantitative synthesis. Psychological Bulletin, 132(3), 354–380.',
  jamieson2010: 'Jamieson, J. P., Mendes, W. B., Blackstock, E. & Schmader, T. (2010). Turning the knots in your stomach into bows: Reappraising arousal improves performance on the GRE. Journal of Experimental Social Psychology, 46(1), 208–212.',
  novaco1975: 'Novaco, R. W. (1975). Anger Control: The Development and Evaluation of an Experimental Treatment. Lexington, MA: Lexington Books.',
  bagwellSchmidt2011: 'Bagwell, C. L. & Schmidt, M. E. (2011). Friendships in Childhood and Adolescence. New York: Guilford.',
  williams2007: 'Williams, K. D. (2007). Ostracism. Annual Review of Psychology, 58, 425–452.',
  steinberg2001: 'Steinberg, L. (2001). We know some things: Parent–adolescent relationships in retrospect and prospect. Journal of Research on Adolescence, 11(1), 1–19.',
  pettigrewTropp2006: 'Pettigrew, T. F. & Tropp, L. R. (2006). A meta-analytic test of intergroup contact theory. Journal of Personality and Social Psychology, 90(5), 751–783.',
  przybylskiWeinstein2017: 'Przybylski, A. K. & Weinstein, N. (2017). A large-scale test of the Goldilocks hypothesis: Quantifying the relations between digital-screen use and the mental well-being of adolescents. Psychological Science, 28(2), 204–215.',
  kingDelfabbro2018: 'King, D. L. & Delfabbro, P. H. (2018). Internet Gaming Disorder: Theory, Assessment, Treatment, and Prevention. London: Academic Press.',
  biddleAsare2011: 'Biddle, S. J. H. & Asare, M. (2011). Physical activity and mental health in children and adolescents: A review of reviews. British Journal of Sports Medicine, 45(11), 886–895.',

  // Skills-Kurs, Jahr 3: Werte, Zukunft, Selbstständigkeit, schwere Gefühle, Mitbestimmung, Medien
  schwartz1992: 'Schwartz, S. H. (1992). Universals in the content and structure of values: Theoretical advances and empirical tests in 20 countries. Advances in Experimental Social Psychology, 25, 1–65.',
  erikson1968: 'Erikson, E. H. (1968). Identity: Youth and Crisis. New York: Norton.',
  super1980: 'Super, D. E. (1980). A life-span, life-space approach to career development. Journal of Vocational Behavior, 16(3), 282–298.',
  holland1997: 'Holland, J. L. (1997). Making Vocational Choices (3rd ed.). Odessa, FL: Psychological Assessment Resources.',
  lusardiMitchell2014: 'Lusardi, A. & Mitchell, O. S. (2014). The economic importance of financial literacy: Theory and evidence. Journal of Economic Literature, 52(1), 5–44.',
  stroebeSchut1999: 'Stroebe, M. & Schut, H. (1999). The dual process model of coping with bereavement: Rationale and description. Death Studies, 23(3), 197–224.',
  worden2009: 'Worden, J. W. (2009). Grief Counseling and Grief Therapy (4th ed.). New York: Springer.',
  tangneyDearing2002: 'Tangney, J. P. & Dearing, R. L. (2002). Shame and Guilt. New York: Guilford.',
  hawkleyCacioppo2010: 'Hawkley, L. C. & Cacioppo, J. T. (2010). Loneliness matters: A theoretical and empirical review of consequences and mechanisms. Annals of Behavioral Medicine, 40(2), 218–227.',
  qualter2015: 'Qualter, P., Vanhalst, J., Harris, R., Van Roekel, E., Lodder, G., Bangee, M., Maes, M. & Verhagen, M. (2015). Loneliness across the life span. Perspectives on Psychological Science, 10(2), 250–264.',
  rickwood2005: 'Rickwood, D., Deane, F. P., Wilson, C. J. & Ciarrochi, J. (2005). Young people’s help-seeking for mental health problems. Australian e-Journal for the Advancement of Mental Health, 4(3), 218–251.',
  hart1992: 'Hart, R. A. (1992). Children’s Participation: From Tokenism to Citizenship. Florenz: UNICEF International Child Development Centre.',
  unKrk1989: 'Vereinte Nationen (1989). Übereinkommen über die Rechte des Kindes. New York: Vereinte Nationen.',
  pariser2011: 'Pariser, E. (2011). The Filter Bubble: What the Internet Is Hiding from You. New York: Penguin Press.',
  unesco2023: 'UNESCO (2023). Guidance for Generative AI in Education and Research. Paris: UNESCO.',
  foshee2004: 'Foshee, V. A., Bauman, K. E., Ennett, S. T., Linder, G. F., Benefield, T. & Suchindran, C. (2004). Assessing the long-term effects of the Safe Dates program and a booster in preventing and reducing adolescent dating violence victimization and perpetration. American Journal of Public Health, 94(4), 619–624.',
  wolfe2009: 'Wolfe, D. A., Crooks, C., Jaffe, P., Chiodo, D., Hughes, R., Ellis, W., Stitt, L. & Donner, A. (2009). A school-based program to prevent adolescent dating violence: A cluster randomized trial. Archives of Pediatrics & Adolescent Medicine, 163(8), 692–699.',

  // Skills-Kurs, Jahr 1: Gruppe, Stabilisierung, Krisen
  yalomLeszcz2005: 'Yalom, I. D. & Leszcz, M. (2005). The Theory and Practice of Group Psychotherapy (5th ed.). New York: Basic Books.',
  reddemann2001: 'Reddemann, L. (2001). Imagination als heilsame Kraft. Zur Behandlung von Traumafolgen mit ressourcenorientierten Verfahren. Stuttgart: Pfeiffer bei Klett-Cotta.',
  senninger2000: 'Senninger, T. (2000). Abenteuer leiten – in Abenteuern lernen. Münster: Ökotopia.',
  hobfoll2007: 'Hobfoll, S. E., Watson, P., Bell, C. C., Bryant, R. A., Brymer, M. J., Friedman, M. J., Friedman, M., Gersons, B. P. R., de Jong, J. T. V. M., Layne, C. M., Maguen, S., Neria, Y., Norwood, A. E., Pynoos, R. S., Reissman, D., Ruzek, J. I., Shalev, A. Y., Solomon, Z., Steinberg, A. M. & Ursano, R. J. (2007). Five essential elements of immediate and mid-term mass trauma intervention: Empirical evidence. Psychiatry, 70(4), 283–315.',
  rose2002: 'Rose, S. C., Bisson, J., Churchill, R. & Wessely, S. (2002). Psychological debriefing for preventing post traumatic stress disorder (PTSD). Cochrane Database of Systematic Reviews, (2), CD000560.',
}

export const QUELLEN_TEXTE = new Set(Object.values(QUELLEN))
