// ---------------------------------------------------------------------------
// Geprüfte Quellen für die Seite „Für die Lehrperson“. Blätter dürfen nur
// Quellen aus dieser Liste nennen (das Prüfskript kontrolliert das) – so
// taucht nie eine erfundene Literaturangabe auf.
// ---------------------------------------------------------------------------

export const QUELLEN: Record<string, string> = {
  // Emotionen & Emotionsregulation
  gross1998: 'Gross, J. J. (1998). The emerging field of emotion regulation: An integrative review. Review of General Psychology, 2(3), 271–299.',
  petermannWiedebusch2016: 'Petermann, F. & Wiedebusch, S. (2016). Emotionale Kompetenz bei Kindern (3. Aufl.). Göttingen: Hogrefe.',
  saarni1999: 'Saarni, C. (1999). The Development of Emotional Competence. New York: Guilford.',
  denham1998: 'Denham, S. A. (1998). Emotional Development in Young Children. New York: Guilford.',
  gottman1997: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child. New York: Simon & Schuster.',
  brackett2019: 'Brackett, M. A. (2019). Permission to Feel. New York: Celadon.',
  siegelBryson2011: 'Siegel, D. J. & Bryson, T. P. (2011). The Whole-Brain Child. New York: Delacorte.',
  linehan2015: 'Linehan, M. M. (2015). DBT Skills Training Manual (2nd ed.). New York: Guilford.',
  rathusMiller2015: 'Rathus, J. H. & Miller, A. L. (2015). DBT Skills Manual for Adolescents. New York: Guilford.',
  kabatZinn1990: 'Kabat-Zinn, J. (1990). Full Catastrophe Living. New York: Delacorte.',
  kendallHedtke2006: 'Kendall, P. C. & Hedtke, K. A. (2006). Cognitive-Behavioral Therapy for Anxious Children: Therapist Manual (3rd ed.). Ardmore, PA: Workbook Publishing.',
  rapee2008: 'Rapee, R. M., Wignall, A., Spence, S. H., Cobham, V. & Lyneham, H. (2008). Helping Your Anxious Child (2nd ed.). Oakland: New Harbinger.',
  zeidner1998: 'Zeidner, M. (1998). Test Anxiety: The State of the Art. New York: Plenum.',
  goleman1995: 'Goleman, D. (1995). Emotional Intelligence. New York: Bantam.',

  // Kognitive Verhaltenstherapie & Selbststeuerung
  ellis1962: 'Ellis, A. (1962). Reason and Emotion in Psychotherapy. New York: Lyle Stuart.',
  beck2011: 'Beck, J. S. (2011). Cognitive Behavior Therapy: Basics and Beyond (2nd ed.). New York: Guilford.',
  meichenbaumGoodman1971: 'Meichenbaum, D. & Goodman, J. (1971). Training impulsive children to talk to themselves. Journal of Abnormal Psychology, 77(2), 115–126.',
  robin1976: 'Robin, A., Schneider, M. & Dolnick, M. (1976). The turtle technique: An extended case study of self-control in the classroom. Psychology in the Schools, 13(4), 449–453.',
  kanfer2012: 'Kanfer, F. H., Reinecker, H. & Schmelzer, D. (2012). Selbstmanagement-Therapie (5. Aufl.). Berlin: Springer.',
  mischel2014: 'Mischel, W. (2014). The Marshmallow Test. New York: Little, Brown.',
  diamond2013: 'Diamond, A. (2013). Executive functions. Annual Review of Psychology, 64, 135–168.',
  barkley2012: 'Barkley, R. A. (2012). Executive Functions: What They Are, How They Work, and Why They Evolved. New York: Guilford.',
  bandura1977: 'Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change. Psychological Review, 84(2), 191–215.',

  // Verhalten, Verstärkung, Schule
  petermann2012: 'Petermann, F. & Petermann, U. (2012). Training mit aggressiven Kindern (13. Aufl.). Weinheim: Beltz.',
  doepfner2019: 'Döpfner, M., Schürmann, S. & Frölich, J. (2019). Therapieprogramm für Kinder mit hyperkinetischem und oppositionellem Problemverhalten THOP (6. Aufl.). Weinheim: Beltz.',
  crone2010: 'Crone, D. A., Hawken, L. S. & Horner, R. H. (2010). Responding to Problem Behavior in Schools: The Behavior Education Program (2nd ed.). New York: Guilford.',
  kazdin2008: 'Kazdin, A. E. (2008). The Kazdin Method for Parenting the Defiant Child. Boston: Houghton Mifflin.',
  premack1959: 'Premack, D. (1959). Toward empirical behavior laws: I. Positive reinforcement. Psychological Review, 66(4), 219–233.',
  nolting2002: 'Nolting, H.-P. (2002). Störungen in der Schulklasse. Weinheim: Beltz.',
  omer2004: 'Omer, H. & von Schlippe, A. (2004). Autorität durch Beziehung. Göttingen: Vandenhoeck & Ruprecht.',
  zehr2002: 'Zehr, H. (2002). The Little Book of Restorative Justice. Intercourse, PA: Good Books.',
  wachtel2016: 'Wachtel, T. (2016). Defining Restorative. Bethlehem, PA: International Institute for Restorative Practices.',
  wood1996: 'Wood, M. M. (1996). Developmental Therapy – Developmental Teaching (3rd ed.). Austin: Pro-Ed.',
  bergsson1998: 'Bergsson, M. & Luckfiel, H. (1998). Umgang mit „schwierigen“ Kindern. Berlin: Cornelsen Scriptor.',

  // Soziales Lernen, Konflikte, Mobbing
  durlak2011: 'Durlak, J. A., Weissberg, R. P., Dymnicki, A. B., Taylor, R. D. & Schellinger, K. B. (2011). The impact of enhancing students’ social and emotional learning: A meta-analysis of school-based universal interventions. Child Development, 82(1), 405–432.',
  taylor2017: 'Taylor, R. D., Oberle, E., Durlak, J. A. & Weissberg, R. P. (2017). Promoting positive youth development through school-based social and emotional learning interventions: A meta-analysis of follow-up effects. Child Development, 88(4), 1156–1171.',
  yeager2017: 'Yeager, D. S. (2017). Social and emotional learning programs for adolescents. The Future of Children, 27(1), 73–94.',
  casel2020: 'CASEL (2020). CASEL’S SEL Framework: What Are the Core Competence Areas and Where Are They Promoted? Chicago: Collaborative for Academic, Social, and Emotional Learning.',
  greenberg1995: 'Greenberg, M. T., Kusché, C. A., Cook, E. T. & Quamma, J. P. (1995). Promoting emotional competence in school-aged children: The effects of the PATHS curriculum. Development and Psychopathology, 7(1), 117–136.',
  websterStratton2003: 'Webster-Stratton, C. & Reid, M. J. (2003). Treating conduct problems and strengthening social and emotional competence in young children: The Dina Dinosaur treatment program. Journal of Emotional and Behavioral Disorders, 11(3), 130–143.',
  shure1992: 'Shure, M. B. (1992). I Can Problem Solve (ICPS). Champaign, IL: Research Press.',
  cierpka2005: 'Cierpka, M. (Hrsg.) (2005). Faustlos – Wie Kinder Konflikte gewaltfrei lösen lernen. Freiburg: Herder.',
  rosenberg2001: 'Rosenberg, M. B. (2001). Gewaltfreie Kommunikation. Paderborn: Junfermann.',
  gordon1972: 'Gordon, T. (1972). Familienkonferenz. Hamburg: Hoffmann und Campe.',
  fisherUry1981: 'Fisher, R. & Ury, W. (1981). Getting to Yes. Boston: Houghton Mifflin.',
  olweus1993: 'Olweus, D. (1993). Bullying at School: What We Know and What We Can Do. Oxford: Blackwell.',
  salmivalli1996: 'Salmivalli, C., Lagerspetz, K., Björkqvist, K., Österman, K. & Kaukiainen, A. (1996). Bullying as a group process: Participant roles and their relations to social status within the group. Aggressive Behavior, 22(1), 1–15.',
  gray2015: 'Gray, C. (2015). The New Social Story Book. Arlington, TX: Future Horizons.',

  // Stärken, Resilienz, Motivation
  masten2014: 'Masten, A. S. (2014). Ordinary Magic: Resilience in Development. New York: Guilford.',
  wernerSmith1992: 'Werner, E. E. & Smith, R. S. (1992). Overcoming the Odds. Ithaca: Cornell University Press.',
  antonovsky1987: 'Antonovsky, A. (1987). Unraveling the Mystery of Health. San Francisco: Jossey-Bass.',
  petersonSeligman2004: 'Peterson, C. & Seligman, M. E. P. (2004). Character Strengths and Virtues. New York: Oxford University Press.',
  seligman2005: 'Seligman, M. E. P., Steen, T. A., Park, N. & Peterson, C. (2005). Positive psychology progress: Empirical validation of interventions. American Psychologist, 60(5), 410–421.',
  deciRyan2000: 'Deci, E. L. & Ryan, R. M. (2000). The “what” and “why” of goal pursuits. Psychological Inquiry, 11(4), 227–268.',
  dweck2006: 'Dweck, C. S. (2006). Mindset: The New Psychology of Success. New York: Random House.',
  gollwitzer1999: 'Gollwitzer, P. M. (1999). Implementation intentions: Strong effects of simple plans. American Psychologist, 54(7), 493–503.',
  oettingen2014: 'Oettingen, G. (2014). Rethinking Positive Thinking. New York: Current.',
  millerRollnick2013: 'Miller, W. R. & Rollnick, S. (2013). Motivational Interviewing (3rd ed.). New York: Guilford.',
  deShazer1985: 'de Shazer, S. (1985). Keys to Solution in Brief Therapy. New York: Norton.',
  steinberg2014: 'Steinberg, L. (2014). Age of Opportunity: Lessons from the New Science of Adolescence. Boston: Houghton Mifflin Harcourt.',

  // Lernen & Organisation
  zimmerman2002: 'Zimmerman, B. J. (2002). Becoming a self-regulated learner: An overview. Theory Into Practice, 41(2), 64–70.',
  dunlosky2013: 'Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J. & Willingham, D. T. (2013). Improving students’ learning with effective learning techniques. Psychological Science in the Public Interest, 14(1), 4–58.',
  hattieTimperley2007: 'Hattie, J. & Timperley, H. (2007). The power of feedback. Review of Educational Research, 77(1), 81–112.',
  steel2007: 'Steel, P. (2007). The nature of procrastination: A meta-analytic and theoretical review of quintessential self-regulatory failure. Psychological Bulletin, 133(1), 65–94.',
  sirois2013: 'Sirois, F. & Pychyl, T. (2013). Procrastination and the priority of short-term mood regulation. Social and Personality Psychology Compass, 7(2), 115–127.',
  cirillo2018: 'Cirillo, F. (2018). The Pomodoro Technique. New York: Currency.',

  // Alltag, Gesundheit, Medien, Visualisierung
  paruthi2016: 'Paruthi, S. et al. (2016). Recommended amount of sleep for pediatric populations: A consensus statement of the American Academy of Sleep Medicine. Journal of Clinical Sleep Medicine, 12(6), 785–786.',
  who2019: 'World Health Organization (2019). Guidelines on physical activity, sedentary behaviour and sleep for children under 5 years of age. Genf: WHO.',
  livingstone2020: 'Livingstone, S. & Blum-Ross, A. (2020). Parenting for a Digital Future. New York: Oxford University Press.',
  beesecure: 'BEE SECURE – Initiative der luxemburgischen Regierung für ein sichereres Internet: www.bee-secure.lu',
  klicksafe: 'klicksafe – EU-Initiative für mehr Sicherheit im Netz: www.klicksafe.de',
  hodgdon1995: 'Hodgdon, L. A. (1995). Visual Strategies for Improving Communication. Troy, MI: QuirkRoberts.',
  mesibov2004: 'Mesibov, G. B., Shea, V. & Schopler, E. (2004). The TEACCH Approach to Autism Spectrum Disorders. New York: Springer.',
  stanleyBrown2012: 'Stanley, B. & Brown, G. K. (2012). Safety planning intervention: A brief intervention to mitigate suicide risk. Cognitive and Behavioral Practice, 19(2), 256–264.',
  rogers1951: 'Rogers, C. R. (1951). Client-Centered Therapy. Boston: Houghton Mifflin.',

  // Skills-Kurs: Gefühle, Körper, Achtsamkeit, Gesundheit
  willcox1982: 'Willcox, G. (1982). The Feeling Wheel: A tool for expanding awareness of emotions and increasing spontaneity and intimacy. Transactional Analysis Journal, 12(4), 274–276.',
  ekman1992: 'Ekman, P. (1992). An argument for basic emotions. Cognition and Emotion, 6(3–4), 169–200.',
  plutchik2001: 'Plutchik, R. (2001). The nature of emotions. American Scientist, 89(4), 344–350.',
  keltnerEkman2015: 'Keltner, D. & Ekman, P. (2015, 3. Juli). The science of “Inside Out”. The New York Times.',
  lieberman2007: 'Lieberman, M. D., Eisenberger, N. I., Crockett, M. J., Tom, S. M., Pfeifer, J. H. & Way, B. M. (2007). Putting feelings into words: Affect labeling disrupts amygdala activity in response to affective stimuli. Psychological Science, 18(5), 421–428.',
  nummenmaa2014: 'Nummenmaa, L., Glerean, E., Hari, R. & Hietanen, J. K. (2014). Bodily maps of emotions. Proceedings of the National Academy of Sciences, 111(2), 646–651.',
  larsen2001: 'Larsen, J. T., McGraw, A. P. & Cacioppo, J. T. (2001). Can people feel happy and sad at the same time? Journal of Personality and Social Psychology, 81(4), 684–696.',
  fredrickson2001: 'Fredrickson, B. L. (2001). The role of positive emotions in positive psychology: The broaden-and-build theory of positive emotions. American Psychologist, 56(3), 218–226.',
  fleischhaker2011: 'Fleischhaker, C., Sixt, B. & Schulz, E. (2011). DBT-A: Dialektisch-behaviorale Therapie für Jugendliche. Berlin: Springer.',
  jacobson1929: 'Jacobson, E. (1929). Progressive Relaxation. Chicago: University of Chicago Press.',
  zaccaro2018: 'Zaccaro, A., Piarulli, A., Laurino, M., Garbella, E., Menicucci, D., Neri, B. & Gemignani, A. (2018). How breath-control can change your life: A systematic review on psycho-physiological correlates of slow breathing. Frontiers in Human Neuroscience, 12, 353.',
  balban2023: 'Balban, M. Y., Neri, E., Kogon, M. M., Weed, L., Nouriani, B., Jo, B., Holl, G., Zeitzer, J. M., Spiegel, D. & Huberman, A. D. (2023). Brief structured respiration practices enhance mood and reduce physiological arousal. Cell Reports Medicine, 4(1), 100895.',
  zenner2014: 'Zenner, C., Herrnleben-Kurz, S. & Walach, H. (2014). Mindfulness-based interventions in schools – a systematic review and meta-analysis. Frontiers in Psychology, 5, 603.',
  hayes2012: 'Hayes, S. C., Strosahl, K. D. & Wilson, K. G. (2012). Acceptance and Commitment Therapy: The Process and Practice of Mindful Change (2nd ed.). New York: Guilford.',
  krossAyduk2017: 'Kross, E. & Ayduk, O. (2017). Self-distancing: Theory, research, and current directions. Advances in Experimental Social Psychology, 55, 81–136.',
  kaplan1995: 'Kaplan, S. (1995). The restorative benefits of nature: Toward an integrative framework. Journal of Environmental Psychology, 15(3), 169–182.',
  lazarusFolkman1984: 'Lazarus, R. S. & Folkman, S. (1984). Stress, Appraisal, and Coping. New York: Springer.',
  who2020: 'World Health Organization (2020). WHO Guidelines on Physical Activity and Sedentary Behaviour. Genf: WHO.',
  carskadon2011: 'Carskadon, M. A. (2011). Sleep in adolescents: The perfect storm. Pediatric Clinics of North America, 58(3), 637–647.',

  // Skills-Kurs: Ich, Stärken, Gedanken
  maslow1943: 'Maslow, A. H. (1943). A theory of human motivation. Psychological Review, 50(4), 370–396.',
  grawe2004: 'Grawe, K. (2004). Neuropsychotherapie. Göttingen: Hogrefe.',
  cain2012: 'Cain, S. (2012). Quiet: The Power of Introverts in a World That Can’t Stop Talking. New York: Crown.',
  luftIngham1955: 'Luft, J. & Ingham, H. (1955). The Johari window, a graphic model of interpersonal awareness. Proceedings of the Western Training Laboratory in Group Development. Los Angeles: University of California.',
  ncube2006: 'Ncube, N. (2006). The Tree of Life Project: Using narrative ideas in work with vulnerable children. International Journal of Narrative Therapy and Community Work, 1, 3–16.',
  harter2012: 'Harter, S. (2012). The Construction of the Self (2nd ed.). New York: Guilford.',
  neff2003: 'Neff, K. D. (2003). Self-compassion: An alternative conceptualization of a healthy attitude toward oneself. Self and Identity, 2(2), 85–101.',
  stallard2019: 'Stallard, P. (2019). Think Good, Feel Good: A Cognitive Behavioural Therapy Workbook for Children and Young People (2nd ed.). Chichester: Wiley.',
  emmonsMcCullough2003: 'Emmons, R. A. & McCullough, M. E. (2003). Counting blessings versus burdens: An experimental investigation of gratitude and subjective well-being in daily life. Journal of Personality and Social Psychology, 84(2), 377–389.',
  pennebaker1997: 'Pennebaker, J. W. (1997). Writing about emotional experiences as a therapeutic process. Psychological Science, 8(3), 162–166.',

  // Skills-Kurs: Gruppe, Kommunikation, Konflikte, Medien
  tuckman1965: 'Tuckman, B. W. (1965). Developmental sequence in small groups. Psychological Bulletin, 63(6), 384–399.',
  coe2012: 'Council of Europe (2012). Compass: Manual for Human Rights Education with Young People (2nd ed.). Strasbourg: Council of Europe Publishing.',
  watzlawick1967: 'Watzlawick, P., Beavin, J. H. & Jackson, D. D. (1967). Pragmatics of Human Communication. New York: Norton.',
  schulzVonThun1981: 'Schulz von Thun, F. (1981). Miteinander reden 1: Störungen und Klärungen. Reinbek: Rowohlt.',
  hall1966: 'Hall, E. T. (1966). The Hidden Dimension. Garden City, NY: Doubleday.',
  glasl1980: 'Glasl, F. (1980). Konfliktmanagement. Bern: Haupt.',
  thomasKilmann1974: 'Thomas, K. W. & Kilmann, R. H. (1974). Thomas-Kilmann Conflict Mode Instrument. Tuxedo, NY: Xicom.',
  asch1956: 'Asch, S. E. (1956). Studies of independence and conformity: I. A minority of one against a unanimous majority. Psychological Monographs: General and Applied, 70(9), 1–70.',
  gardnerSteinberg2005: 'Gardner, M. & Steinberg, L. (2005). Peer influence on risk taking, risk preference, and risky decision making in adolescence and adulthood: An experimental study. Developmental Psychology, 41(4), 625–635.',
  lataneDarley1970: 'Latané, B. & Darley, J. M. (1970). The Unresponsive Bystander: Why Doesn’t He Help? New York: Appleton-Century-Crofts.',
  kaerna2011: 'Kärnä, A., Voeten, M., Little, T. D., Poskiparta, E., Kaljonen, A. & Salmivalli, C. (2011). A large-scale evaluation of the KiVa antibullying program: Grades 4–6. Child Development, 82(1), 311–330.',
  hindujaPatchin2015: 'Hinduja, S. & Patchin, J. W. (2015). Bullying Beyond the Schoolyard (2nd ed.). Thousand Oaks, CA: Corwin.',
  orbenPrzybylski2019: 'Orben, A. & Przybylski, A. K. (2019). The association between adolescent well-being and digital technology use. Nature Human Behaviour, 3(2), 173–182.',
  fardouly2015: 'Fardouly, J., Diedrichs, P. C., Vartanian, L. R. & Halliwell, E. (2015). Social comparisons on social media: The impact of Facebook on young women’s body image concerns and mood. Body Image, 13, 38–45.',
  roozenbeek2019: 'Roozenbeek, J. & van der Linden, S. (2019). Fake news game confers psychological resistance against online misinformation. Palgrave Communications, 5, 65.',
  wineburgMcGrew2019: 'Wineburg, S. & McGrew, S. (2019). Lateral reading and the nature of expertise: Reading less and learning more when evaluating digital information. Teachers College Record, 121(11), 1–40.',
  allport1954: 'Allport, G. W. (1954). The Nature of Prejudice. Cambridge, MA: Addison-Wesley.',

  // Skills-Kurs, Jahr 2 und 3: Selbstwert, Schule, Wut, Beziehungen, Vielfalt, Netz, Gesundheit
  rosenberg1965: 'Rosenberg, M. (1965). Society and the Adolescent Self-Image. Princeton, NJ: Princeton University Press.',
  crockerWolfe2001: 'Crocker, J. & Wolfe, C. T. (2001). Contingencies of self-worth. Psychological Review, 108(3), 593–623.',
  roedigerKarpicke2006: 'Roediger, H. L. & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. Psychological Science, 17(3), 249–255.',
  cepeda2006: 'Cepeda, N. J., Pashler, H., Vul, E., Wixted, J. T. & Rohrer, D. (2006). Distributed practice in verbal recall tasks: A review and quantitative synthesis. Psychological Bulletin, 132(3), 354–380.',
  jamieson2010: 'Jamieson, J. P., Mendes, W. B., Blackstock, E. & Schmader, T. (2010). Turning the knots in your stomach into bows: Reappraising arousal improves performance on the GRE. Journal of Experimental Social Psychology, 46(1), 208–212.',
  novaco1975: 'Novaco, R. W. (1975). Anger Control: The Development and Evaluation of an Experimental Treatment. Lexington, MA: Lexington Books.',
  bagwellSchmidt2011: 'Bagwell, C. L. & Schmidt, M. E. (2011). Friendships in Childhood and Adolescence. New York: Guilford.',
  williams2007: 'Williams, K. D. (2007). Ostracism. Annual Review of Psychology, 58, 425–452.',
  steinberg2001: 'Steinberg, L. (2001). We know some things: Parent–adolescent relationships in retrospect and prospect. Journal of Research on Adolescence, 11(1), 1–19.',
  pettigrewTropp2006: 'Pettigrew, T. F. & Tropp, L. R. (2006). A meta-analytic test of intergroup contact theory. Journal of Personality and Social Psychology, 90(5), 751–783.',
  przybylskiWeinstein2017: 'Przybylski, A. K. & Weinstein, N. (2017). A large-scale test of the Goldilocks hypothesis: Quantifying the relations between digital-screen use and the mental well-being of adolescents. Psychological Science, 28(2), 204–215.',
  kingDelfabbro2018: 'King, D. L. & Delfabbro, P. H. (2018). Internet Gaming Disorder: Theory, Assessment, Treatment, and Prevention. London: Academic Press.',
  biddleAsare2011: 'Biddle, S. J. H. & Asare, M. (2011). Physical activity and mental health in children and adolescents: A review of reviews. British Journal of Sports Medicine, 45(11), 886–895.',

  // Skills-Kurs, Jahr 3: Werte, Zukunft, Selbstständigkeit, schwere Gefühle, Mitbestimmung, Medien
  schwartz1992: 'Schwartz, S. H. (1992). Universals in the content and structure of values: Theoretical advances and empirical tests in 20 countries. Advances in Experimental Social Psychology, 25, 1–65.',
  erikson1968: 'Erikson, E. H. (1968). Identity: Youth and Crisis. New York: Norton.',
  super1980: 'Super, D. E. (1980). A life-span, life-space approach to career development. Journal of Vocational Behavior, 16(3), 282–298.',
  holland1997: 'Holland, J. L. (1997). Making Vocational Choices (3rd ed.). Odessa, FL: Psychological Assessment Resources.',
  lusardiMitchell2014: 'Lusardi, A. & Mitchell, O. S. (2014). The economic importance of financial literacy: Theory and evidence. Journal of Economic Literature, 52(1), 5–44.',
  stroebeSchut1999: 'Stroebe, M. & Schut, H. (1999). The dual process model of coping with bereavement: Rationale and description. Death Studies, 23(3), 197–224.',
  worden2009: 'Worden, J. W. (2009). Grief Counseling and Grief Therapy (4th ed.). New York: Springer.',
  tangneyDearing2002: 'Tangney, J. P. & Dearing, R. L. (2002). Shame and Guilt. New York: Guilford.',
  hawkleyCacioppo2010: 'Hawkley, L. C. & Cacioppo, J. T. (2010). Loneliness matters: A theoretical and empirical review of consequences and mechanisms. Annals of Behavioral Medicine, 40(2), 218–227.',
  qualter2015: 'Qualter, P., Vanhalst, J., Harris, R., Van Roekel, E., Lodder, G., Bangee, M., Maes, M. & Verhagen, M. (2015). Loneliness across the life span. Perspectives on Psychological Science, 10(2), 250–264.',
  rickwood2005: 'Rickwood, D., Deane, F. P., Wilson, C. J. & Ciarrochi, J. (2005). Young people’s help-seeking for mental health problems. Australian e-Journal for the Advancement of Mental Health, 4(3), 218–251.',
  hart1992: 'Hart, R. A. (1992). Children’s Participation: From Tokenism to Citizenship. Florenz: UNICEF International Child Development Centre.',
  unKrk1989: 'Vereinte Nationen (1989). Übereinkommen über die Rechte des Kindes. New York: Vereinte Nationen.',
  pariser2011: 'Pariser, E. (2011). The Filter Bubble: What the Internet Is Hiding from You. New York: Penguin Press.',
  unesco2023: 'UNESCO (2023). Guidance for Generative AI in Education and Research. Paris: UNESCO.',
  foshee2004: 'Foshee, V. A., Bauman, K. E., Ennett, S. T., Linder, G. F., Benefield, T. & Suchindran, C. (2004). Assessing the long-term effects of the Safe Dates program and a booster in preventing and reducing adolescent dating violence victimization and perpetration. American Journal of Public Health, 94(4), 619–624.',
  wolfe2009: 'Wolfe, D. A., Crooks, C., Jaffe, P., Chiodo, D., Hughes, R., Ellis, W., Stitt, L. & Donner, A. (2009). A school-based program to prevent adolescent dating violence: A cluster randomized trial. Archives of Pediatrics & Adolescent Medicine, 163(8), 692–699.',

  // Skills-Kurs, Jahr 1: Gruppe, Stabilisierung, Krisen
  yalomLeszcz2005: 'Yalom, I. D. & Leszcz, M. (2005). The Theory and Practice of Group Psychotherapy (5th ed.). New York: Basic Books.',
  reddemann2001: 'Reddemann, L. (2001). Imagination als heilsame Kraft. Zur Behandlung von Traumafolgen mit ressourcenorientierten Verfahren. Stuttgart: Pfeiffer bei Klett-Cotta.',
  senninger2000: 'Senninger, T. (2000). Abenteuer leiten – in Abenteuern lernen. Münster: Ökotopia.',
  hobfoll2007: 'Hobfoll, S. E., Watson, P., Bell, C. C., Bryant, R. A., Brymer, M. J., Friedman, M. J., Friedman, M., Gersons, B. P. R., de Jong, J. T. V. M., Layne, C. M., Maguen, S., Neria, Y., Norwood, A. E., Pynoos, R. S., Reissman, D., Ruzek, J. I., Shalev, A. Y., Solomon, Z., Steinberg, A. M. & Ursano, R. J. (2007). Five essential elements of immediate and mid-term mass trauma intervention: Empirical evidence. Psychiatry, 70(4), 283–315.',
  rose2002: 'Rose, S. C., Bisson, J., Churchill, R. & Wessely, S. (2002). Psychological debriefing for preventing post traumatic stress disorder (PTSD). Cochrane Database of Systematic Reviews, (2), CD000560.',

  // Skills-Kurs, Jahr 2 und 3: Liebe, Sexualität, Einvernehmlichkeit
  whoBzga2010: 'WHO Regional Office for Europe & BZgA (2010). Standards for Sexuality Education in Europe: A Framework for Policy Makers, Educational and Health Authorities and Specialists. Köln: Bundeszentrale für gesundheitliche Aufklärung.',
  unesco2018: 'UNESCO (2018). International Technical Guidance on Sexuality Education: An Evidence-Informed Approach (revised ed.). Paris: UNESCO.',
  collins2003: 'Collins, W. A. (2003). More than myth: The developmental significance of romantic relationships during adolescence. Journal of Research on Adolescence, 13(1), 1–24.',
  beres2007: 'Beres, M. A. (2007). ‘Spontaneous’ sexual consent: An analysis of sexual consent literature. Feminism & Psychology, 17(1), 93–108.',
  madigan2018: 'Madigan, S., Ly, A., Rash, C. L., Van Ouytsel, J. & Temple, J. R. (2018). Prevalence of multiple forms of sexting behavior among youth: A systematic review and meta-analysis. JAMA Pediatrics, 172(4), 327–335.',
  wolak2018: 'Wolak, J., Finkelhor, D., Walsh, W. & Treitman, L. (2018). Sextortion of minors: Characteristics and dynamics. Journal of Adolescent Health, 62(1), 72–79.',

  // Skills-Kurs, Jahr 2 und 3: Alkohol, Nikotin, Cannabis
  squeglia2009: 'Squeglia, L. M., Jacobus, J. & Tapert, S. F. (2009). The influence of substance use on adolescent brain development. Clinical EEG and Neuroscience, 40(1), 31–38.',
  volkow2014: 'Volkow, N. D., Baler, R. D., Compton, W. M. & Weiss, S. R. B. (2014). Adverse health effects of marijuana use. New England Journal of Medicine, 370(23), 2219–2227.',
  perkins2002: 'Perkins, H. W. (2002). Social norms and the prevention of alcohol misuse in collegiate contexts. Journal of Studies on Alcohol, Supplement 14, 164–172.',
  petersRuiterKok2013: 'Peters, G.-J. Y., Ruiter, R. A. C. & Kok, G. (2013). Threatening communication: A critical re-analysis and a revised meta-analytic test of fear appeal theory. Health Psychology Review, 7(Suppl. 1), S8–S31.',
  faggiano2014: 'Faggiano, F., Minozzi, S., Versino, E. & Buscemi, D. (2014). Universal school-based prevention for illicit drug use. Cochrane Database of Systematic Reviews, (12), CD003020.',
  foxcroftTsertsvadze2011: 'Foxcroft, D. R. & Tsertsvadze, A. (2011). Universal school-based prevention programs for alcohol misuse in young people. Cochrane Database of Systematic Reviews, (5), CD009113.',

  // Skills-Kurs, Jahr 2 und 3: Krisen, Selbstverletzung, Suizidprävention
  who2017: 'World Health Organization (2017). Preventing Suicide: A Resource for Media Professionals (update 2017). Genf: WHO.',
  wasserman2015: 'Wasserman, D., Hoven, C. W., Wasserman, C., Wall, M., Eisenberg, R., Hadlaczky, G. et al. (2015). School-based suicide prevention programmes: The SEYLE cluster-randomised, controlled trial. The Lancet, 385(9977), 1536–1544.',
  dazzi2014: 'Dazzi, T., Gribble, R., Wessely, S. & Fear, N. T. (2014). Does asking about suicide and related behaviours induce suicidal ideation? What is the evidence? Psychological Medicine, 44(16), 3361–3363.',
  hawton2012: 'Hawton, K., Saunders, K. E. A. & O’Connor, R. C. (2012). Self-harm and suicide in adolescents. The Lancet, 379(9834), 2373–2382.',
  kitchenerJorm2002: 'Kitchener, B. A. & Jorm, A. F. (2002). Mental health first aid training for the public: Evaluation of effects on knowledge, attitudes and helping behavior. BMC Psychiatry, 2, 10.',

  // Skills-Kurs: Grundlagen, die mehrere Einheiten nutzen
  craig2002: 'Craig, A. D. (2002). How do you feel? Interoception: The sense of the physiological condition of the body. Nature Reviews Neuroscience, 3(8), 655–666.',
  juslinVastfjall2008: 'Juslin, P. N. & Västfjäll, D. (2008). Emotional responses to music: The need to consider underlying mechanisms. Behavioral and Brain Sciences, 31(5), 559–575.',
  wegner1987: 'Wegner, D. M., Schneider, D. J., Carter, S. R. & White, T. L. (1987). Paradoxical effects of thought suppression. Journal of Personality and Social Psychology, 53(1), 5–13.',
  padesky1994: 'Padesky, C. A. (1994). Schema change processes in cognitive therapy. Clinical Psychology & Psychotherapy, 1(5), 267–278.',
  tuckmanJensen1977: 'Tuckman, B. W. & Jensen, M. A. C. (1977). Stages of small-group development revisited. Group & Organization Studies, 2(4), 419–427.',
  lally2010: 'Lally, P., van Jaarsveld, C. H. M., Potts, H. W. W. & Wardle, J. (2010). How are habits formed: Modelling habit formation in the real world. European Journal of Social Psychology, 40(6), 998–1009.',
  leavittMueller1951: 'Leavitt, H. J. & Mueller, R. A. H. (1951). Some effects of feedback on communication. Human Relations, 4(4), 401–410.',
  kruger2005: 'Kruger, J., Epley, N., Parker, J. & Ng, Z.-W. (2005). Egocentrism over e-mail: Can we communicate as well as we think? Journal of Personality and Social Psychology, 89(6), 925–936.',

  // Skills-Kurs, Jahr 2 und 3: Nachträge aus den Einheiten
  // Freundschaft, Zugehörigkeit, Selbstwert, Selbstmitgefühl
  zadro2004: 'Zadro, L., Williams, K. D. & Richardson, R. (2004). How low can you go? Ostracism by a computer is sufficient to lower self-reported levels of belonging, control, self-esteem, and meaningful existence. Journal of Experimental Social Psychology, 40(4), 560–567.',
  newcombBagwell1995: 'Newcomb, A. F. & Bagwell, C. L. (1995). Children’s friendship relations: A meta-analytic review. Psychological Bulletin, 117(2), 306–347.',
  hutcherson2008: 'Hutcherson, C. A., Seppala, E. M. & Gross, J. J. (2008). Loving-kindness meditation increases social connectedness. Emotion, 8(5), 720–724.',
  neff2011: 'Neff, K. D. (2011). Self-Compassion: The Proven Power of Being Kind to Yourself. New York: William Morrow.',
  neffMcGehee2010: 'Neff, K. D. & McGehee, P. (2010). Self-compassion and psychological resilience among adolescents and young adults. Self and Identity, 9(3), 225–240.',
  breinesChen2012: 'Breines, J. G. & Chen, S. (2012). Self-compassion increases self-improvement motivation. Personality and Social Psychology Bulletin, 38(9), 1133–1143.',
  crocker2003: 'Crocker, J., Luhtanen, R. K., Cooper, M. L. & Bouvrette, A. (2003). Contingencies of self-worth in college students: Theory and measurement. Journal of Personality and Social Psychology, 85(5), 894–908.',
  alleva2015: 'Alleva, J. M., Martijn, C., Van Breukelen, G. J. P., Jansen, A. & Karos, K. (2015). Expand Your Horizon: A programme that improves body image and reduces self-objectification by training women to focus on body functionality. Body Image, 15, 81–89.',
  smetana1988: 'Smetana, J. G. (1988). Adolescents’ and parents’ conceptions of parental authority. Child Development, 59(2), 321–335.',
  // Identität, Werte, Ziele, Entscheidungen
  marcia1966: 'Marcia, J. E. (1966). Development and validation of ego-identity status. Journal of Personality and Social Psychology, 3(5), 551–558.',
  markusNurius1986: 'Markus, H. & Nurius, P. (1986). Possible selves. American Psychologist, 41(9), 954–969.',
  busch2012: 'Busch, B. (2012). The linguistic repertoire revisited. Applied Linguistics, 33(5), 503–523.',
  simonHoweKirschenbaum1972: 'Simon, S. B., Howe, L. W. & Kirschenbaum, H. (1972). Values Clarification: A Handbook of Practical Strategies for Teachers and Students. New York: Hart.',
  duckworth2011: 'Duckworth, A. L., Grant, H., Loew, B., Oettingen, G. & Gollwitzer, P. M. (2011). Self-regulation strategies improve self-discipline in adolescents: Benefits of mental contrasting and implementation intentions. Educational Psychology, 31(1), 17–26.',
  gollwitzerSheeran2006: 'Gollwitzer, P. M. & Sheeran, P. (2006). Implementation intentions and goal achievement: A meta-analysis of effects and processes. Advances in Experimental Social Psychology, 38, 69–119.',
  banduraSchunk1981: 'Bandura, A. & Schunk, D. H. (1981). Cultivating competence, self-efficacy, and intrinsic interest through proximal self-motivation. Journal of Personality and Social Psychology, 41(3), 586–598.',
  grossmannKross2014: 'Grossmann, I. & Kross, E. (2014). Exploring Solomon’s paradox: Self-distancing eliminates the self-other asymmetry in wise reasoning about close relationships in younger and older adults. Psychological Science, 25(8), 1571–1580.',
  chein2011: 'Chein, J., Albert, D., O’Brien, L., Uckert, K. & Steinberg, L. (2011). Peers increase adolescent risk taking by enhancing activity in the brain’s reward circuitry. Developmental Science, 14(2), F1–F10.',
  sisk2018: 'Sisk, V. F., Burgoyne, A. P., Sun, J., Butler, J. L. & Macnamara, B. N. (2018). To what extent and under which circumstances are growth mind-sets important to academic achievement? Two meta-analyses. Psychological Science, 29(4), 549–571.',
  yerkesDodson1908: 'Yerkes, R. M. & Dodson, J. D. (1908). The relation of strength of stimulus to rapidity of habit-formation. Journal of Comparative Neurology and Psychology, 18(5), 459–482.',
  // Gruppe, Vorurteile, Kommunikation, Beteiligung
  tajfel1971: 'Tajfel, H., Billig, M. G., Bundy, R. P. & Flament, C. (1971). Social categorization and intergroup behaviour. European Journal of Social Psychology, 1(2), 149–178.',
  sherif1961: 'Sherif, M., Harvey, O. J., White, B. J., Hood, W. R. & Sherif, C. W. (1961). Intergroup Conflict and Cooperation: The Robbers Cave Experiment. Norman, OK: University Book Exchange.',
  boal1979: 'Boal, A. (1979). Theatre of the Oppressed. London: Pluto Press.',
  rogersRoethlisberger1952: 'Rogers, C. R. & Roethlisberger, F. J. (1952). Barriers and gateways to communication. Harvard Business Review, 30(4), 46–52.',
  palacio2012: 'Palacio, R. J. (2012). Wonder. New York: Alfred A. Knopf.',
  // Netz, Medien, KI, Gaming
  suler2004: 'Suler, J. (2004). The online disinhibition effect. CyberPsychology & Behavior, 7(3), 321–326.',
  przybylski2010: 'Przybylski, A. K., Rigby, C. S. & Ryan, R. M. (2010). A motivational model of video game engagement. Review of General Psychology, 14(2), 154–166.',
  zendleCairns2018: 'Zendle, D. & Cairns, P. (2018). Video game loot boxes are linked to problem gambling: Results of a large-scale survey. PLOS ONE, 13(11), e0206767.',
  bakshy2015: 'Bakshy, E., Messing, S. & Adamic, L. A. (2015). Exposure to ideologically diverse news and opinion on Facebook. Science, 348(6239), 1130–1132.',
  zuiderveenBorgesius2016: 'Zuiderveen Borgesius, F. J., Trilling, D., Möller, J., Bodó, B., de Vreese, C. H. & Helberger, N. (2016). Should we worry about filter bubbles? Internet Policy Review, 5(1).',
  ji2023: 'Ji, Z., Lee, N., Frieske, R., Yu, T., Su, D., Xu, Y., Ishii, E., Bang, Y. J., Madotto, A. & Fung, P. (2023). Survey of hallucination in natural language generation. ACM Computing Surveys, 55(12), 1–38.',
  euDsa2022: 'Verordnung (EU) 2022/2065 des Europäischen Parlaments und des Rates vom 19. Oktober 2022 über einen Binnenmarkt für digitale Dienste (Gesetz über digitale Dienste). Amtsblatt der EU, L 277, 1–102.',
  // Gesundheit: Schlaf, Ernährung, Bewegung, Alltag
  efsa2015: 'EFSA Panel on Dietetic Products, Nutrition and Allergies (NDA) (2015). Scientific Opinion on the safety of caffeine. EFSA Journal, 13(5), 4102.',
  scullin2018: 'Scullin, M. K., Krueger, M. L., Ballard, H. K., Pruett, N. & Bliwise, D. L. (2018). The effects of bedtime writing on difficulty falling asleep: A polysomnographic study comparing to-do lists and completed activity lists. Journal of Experimental Psychology: General, 147(1), 139–146.',
  haleGuan2015: 'Hale, L. & Guan, S. (2015). Screen time and sleep among school-aged children and adolescents: A systematic literature review. Sleep Medicine Reviews, 21, 50–58.',
  wittmann2006: 'Wittmann, M., Dinich, J., Merrow, M. & Roenneberg, T. (2006). Social jetlag: Misalignment of biological and social time. Chronobiology International, 23(1–2), 497–509.',
  adolphus2013: 'Adolphus, K., Lawton, C. L. & Dye, L. (2013). The effects of breakfast on behavior and academic performance in children and adolescents. Frontiers in Human Neuroscience, 7, 425.',
  neumarkSztainer2006: 'Neumark-Sztainer, D., Wall, M., Guo, J., Story, M., Haines, J. & Eisenberg, M. (2006). Obesity, disordered eating, and eating disorders in a longitudinal study of adolescents: How do dieters fare 5 years later? Journal of the American Dietetic Association, 106(4), 559–568.',
  who2006: 'World Health Organization (2006). Five Keys to Safer Food Manual. Genf: WHO.',
  eu1169_2011: 'Verordnung (EU) Nr. 1169/2011 des Europäischen Parlaments und des Rates vom 25. Oktober 2011 betreffend die Information der Verbraucher über Lebensmittel. Amtsblatt der EU, L 304, 18–63.',
  eu2011_83: 'Richtlinie 2011/83/EU des Europäischen Parlaments und des Rates vom 25. Oktober 2011 über die Rechte der Verbraucher. Amtsblatt der EU, L 304, 64–88.',
  // Alkohol, Nikotin, Konsum, Erste Hilfe
  cooper1994: 'Cooper, M. L. (1994). Motivations for alcohol use among adolescents: Development and validation of a four-factor model. Psychological Assessment, 6(2), 117–128.',
  parrott1999: 'Parrott, A. C. (1999). Does cigarette smoking cause stress? American Psychologist, 54(10), 817–820.',
  bowenMarlatt2009: 'Bowen, S. & Marlatt, A. (2009). Surfing the urge: Brief mindfulness-based intervention for college student smokers. Psychology of Addictive Behaviors, 23(4), 666–671.',
  usdhhs2016: 'U.S. Department of Health and Human Services (2016). E-Cigarette Use Among Youth and Young Adults: A Report of the Surgeon General. Atlanta, GA: Centers for Disease Control and Prevention.',
  zideman2021: 'Zideman, D. A., Singletary, E. M., Borra, V., Cassan, P., Cimpoesu, C. D., De Buck, E., Djärv, T., Handley, A. J., Klaassen, B., Meyran, D., Oliver, E. & Poole, K. (2021). European Resuscitation Council Guidelines 2021: First aid. Resuscitation, 161, 270–290.',
  // Belastung, Hilfe holen, Resilienz, Suizidprävention
  hart2018: 'Hart, L. M., Morgan, A. J., Rossetto, A., Kelly, C. M., Mackinnon, A. & Jorm, A. F. (2018). Helping adolescents to better support their peers with a mental health problem: A cluster-randomised crossover trial of teen Mental Health First Aid. Australian & New Zealand Journal of Psychiatry, 52(7), 638–651.',
  stanley2018: 'Stanley, B., Brown, G. K., Brenner, L. A., Galfalvy, H. C., Currier, G. W., Knox, K. L., Chaudhury, S. R., Bush, A. L. & Green, K. L. (2018). Comparison of the Safety Planning Intervention with follow-up vs usual care of suicidal patients treated in the emergency department. JAMA Psychiatry, 75(9), 894–900.',
  niederkrotenthaler2010: 'Niederkrotenthaler, T., Voracek, M., Herberth, A., Till, B., Strauss, M., Etzersdorfer, E., Eisenwort, B. & Sonneck, G. (2010). Role of media reports in completed and prevented suicide: Werther v. Papageno effects. British Journal of Psychiatry, 197(3), 234–243.',
  masi2011: 'Masi, C. M., Chen, H.-Y., Hawkley, L. C. & Cacioppo, J. T. (2011). A meta-analysis of interventions to reduce loneliness. Personality and Social Psychology Review, 15(3), 219–266.',
  gulliver2010: 'Gulliver, A., Griffiths, K. M. & Christensen, H. (2010). Perceived barriers and facilitators to mental health help-seeking in young people: A systematic review. BMC Psychiatry, 10, 113.',
  grotberg1995: 'Grotberg, E. H. (1995). A Guide to Promoting Resilience in Children: Strengthening the Human Spirit. Den Haag: Bernard van Leer Foundation.',
  baumeister2001: 'Baumeister, R. F., Bratslavsky, E., Finkenauer, C. & Vohs, K. D. (2001). Bad is stronger than good. Review of General Psychology, 5(4), 323–370.',
  froh2008: 'Froh, J. J., Sefick, W. J. & Emmons, R. A. (2008). Counting blessings in early adolescents: An experimental study of gratitude and subjective well-being. Journal of School Psychology, 46(2), 213–233.',
  bryantVeroff2007: 'Bryant, F. B. & Veroff, J. (2007). Savoring: A New Model of Positive Experience. Mahwah, NJ: Lawrence Erlbaum.',
  jekaLackner1994: 'Jeka, J. J. & Lackner, J. R. (1994). Fingertip contact influences human postural control. Experimental Brain Research, 100(3), 495–502.',
  // Übergänge nach dem Kurs
  eccles2011: 'Eccles, J. S. & Roeser, R. W. (2011). Schools as developmental contexts during adolescence. Journal of Research on Adolescence, 21(1), 225–241.',
  schlossberg1981: 'Schlossberg, N. K. (1981). A model for analyzing human adaptation to transition. The Counseling Psychologist, 9(2), 2–18.',
  marlattGordon1985: 'Marlatt, G. A. & Gordon, J. R. (Eds.) (1985). Relapse Prevention: Maintenance Strategies in the Treatment of Addictive Behaviors. New York: Guilford.',

  // Förderfach, Wirkungs-Check: Wirksamkeit und Umsetzung von Programmen
  cipriano2023: 'Cipriano, C., Strambler, M. J., Naples, L. H., Ha, C., Kirk, M., Wood, M. et al. (2023). The state of evidence for social and emotional learning: A contemporary meta-analysis of universal school-based SEL interventions. Child Development, 94(5), 1181–1204.',
  durlakDuPre2008: 'Durlak, J. A. & DuPre, E. P. (2008). Implementation matters: A review of research on the influence of implementation on program outcomes and the factors affecting implementation. American Journal of Community Psychology, 41(3–4), 327–350.',
  howardDailey1979: 'Howard, G. S. & Dailey, P. R. (1979). Response-shift bias: A source of contamination of self-report measures. Journal of Applied Psychology, 64(2), 144–150.',
  tobler2000: 'Tobler, N. S., Roona, M. R., Ochshorn, P., Marshall, D. G., Streke, A. V. & Stackpole, K. M. (2000). School-based adolescent drug prevention programs: 1998 meta-analysis. Journal of Primary Prevention, 20(4), 275–336.',
  petrosino2013: 'Petrosino, A., Turpin-Petrosino, C., Hollis-Peel, M. E. & Lavenberg, J. G. (2013). ‘Scared Straight’ and other juvenile awareness programs for preventing juvenile delinquency. Cochrane Database of Systematic Reviews, (4), CD002796.',
  dishion1999: 'Dishion, T. J., McCord, J. & Poulin, F. (1999). When interventions harm: Peer groups and problem behavior. American Psychologist, 54(9), 755–764.',
  stallard2014: 'Stallard, P., Skryabina, E., Taylor, G., Phillips, R., Daniels, H., Anderson, R. & Simpson, N. (2014). Classroom-based cognitive behaviour therapy (FRIENDS): A cluster randomised controlled trial to Prevent Anxiety in Children through Education in Schools (PACES). The Lancet Psychiatry, 1(3), 185–192.',
  challen2014: 'Challen, A. R., Machin, S. J. & Gillham, J. E. (2014). The UK Resilience Programme: A school-based universal nonrandomized pragmatic controlled trial. Journal of Consulting and Clinical Psychology, 82(1), 75–89.',
  kuyken2022: 'Kuyken, W., Ball, S., Crane, C., Ganguli, P., Jones, B., Montero-Marin, J. et al. (2022). Effectiveness and cost-effectiveness of universal school-based mindfulness training compared with normal school provision in reducing risk of mental health problems and promoting well-being in adolescence: The MYRIAD cluster randomised controlled trial. Evidence-Based Mental Health, 25(3), 99–109.',
  dunning2019: 'Dunning, D. L., Griffiths, K., Kuyken, W., Crane, C., Foulkes, L., Parker, J. & Dalgleish, T. (2019). Research Review: The effects of mindfulness-based interventions on cognition and mental health in children and adolescents – a meta-analysis of randomized controlled trials. Journal of Child Psychology and Psychiatry, 60(3), 244–258.',
  foulkesStringaris2023: 'Foulkes, L. & Stringaris, A. (2023). Do no harm: Can school mental health interventions cause iatrogenic harm? BJPsych Bulletin, 47(5), 267–269.',
  foulkesAndrews2023: 'Foulkes, L. & Andrews, J. L. (2023). Are mental health awareness efforts contributing to the rise in reported mental health problems? A call to test the prevalence inflation hypothesis. New Ideas in Psychology, 69, 101010.',
  mazza2016: 'Mazza, J. J., Dexter-Mazza, E. T., Miller, A. L., Rathus, J. H. & Murphy, H. E. (2016). DBT Skills in Schools: Skills Training for Emotional Problem Solving for Adolescents (DBT STEPS-A). New York: Guilford.',
  flynn2018: 'Flynn, D., Joyce, M., Weihrauch, M. & Corcoran, P. (2018). Innovations in Practice: Dialectical behaviour therapy – skills training for emotional problem solving for adolescents (DBT STEPS-A): Evaluation of a pilot implementation in Irish post-primary schools. Child and Adolescent Mental Health, 23(4), 376–380.',
  // Förderfach, Wirkungs-Check: Jugendalter, Status, Zugehörigkeit, Selbstbild
  yeagerDahlDweck2018: 'Yeager, D. S., Dahl, R. E. & Dweck, C. S. (2018). Why interventions to influence adolescent behavior often fail but could succeed. Perspectives on Psychological Science, 13(1), 101–122.',
  bryanYeager2016: 'Bryan, C. J., Yeager, D. S., Hinojosa, C. P., Chabot, A., Bergen, H., Kawamura, M. & Steubing, F. (2016). Harnessing adolescent values to motivate healthier eating. Proceedings of the National Academy of Sciences, 113(39), 10830–10835.',
  yeagerHanselman2019: 'Yeager, D. S., Hanselman, P., Walton, G. M., Murray, J. S., Crosnoe, R., Muller, C. et al. (2019). A national experiment reveals where a growth mindset improves achievement. Nature, 573(7774), 364–369.',
  yeagerBryan2022: 'Yeager, D. S., Bryan, C. J., Gross, J. J., Murray, J. S., Krettek Cobb, D., Santos, P. H. F. et al. (2022). A synergistic mindsets intervention protects adolescents from stress. Nature, 607(7919), 512–520.',
  waltonCohen2011: 'Walton, G. M. & Cohen, G. L. (2011). A brief social-belonging intervention improves academic and health outcomes of minority students. Science, 331(6023), 1447–1451.',
  roseth2008: 'Roseth, C. J., Johnson, D. W. & Johnson, R. T. (2008). Promoting early adolescents’ achievement and peer relationships: The effects of cooperative, competitive, and individualistic goal structures. Psychological Bulletin, 134(2), 223–246.',
  brooks2014: 'Brooks, A. W. (2014). Get excited: Reappraising pre-performance anxiety as excitement. Journal of Experimental Psychology: General, 143(3), 1144–1158.',
  duckworthKirby2013: 'Duckworth, A. L., Kirby, T. A., Gollwitzer, A. & Oettingen, G. (2013). From fantasy to action: Mental contrasting with implementation intentions (MCII) improves academic performance in children. Social Psychological and Personality Science, 4(6), 745–753.',
  // Förderfach, Wirkungs-Check: Emotionsregulation, Gedanken, Körperbild, Selbstmitgefühl
  sheppes2011: 'Sheppes, G., Scheibe, S., Suri, G. & Gross, J. J. (2011). Emotion-regulation choice. Psychological Science, 22(11), 1391–1396.',
  masuda2004: 'Masuda, A., Hayes, S. C., Sackett, C. F. & Twohig, M. P. (2004). Cognitive defusion and self-relevant negative thoughts: Examining the impact of a ninety year old technique. Behaviour Research and Therapy, 42(4), 477–485.',
  brackett2012: 'Brackett, M. A., Rivers, S. E., Reyes, M. R. & Salovey, P. (2012). Enhancing academic performance and social and emotional competence with the RULER feeling words curriculum. Learning and Individual Differences, 22(2), 218–224.',
  yager2013: 'Yager, Z., Diedrichs, P. C., Ricciardelli, L. A. & Halliwell, E. (2013). What works in secondary schools? A systematic review of classroom-based body image programs. Body Image, 10(3), 271–281.',
  diedrichs2015: 'Diedrichs, P. C., Atkinson, M. J., Steer, R. J., Garbett, K. M., Rumsey, N. & Halliwell, E. (2015). Effectiveness of a brief school-based body image intervention ‘Dove Confident Me: Single Session’ when delivered by teachers and researchers: Results from a cluster randomised controlled trial. Behaviour Research and Therapy, 74, 94–104.',
  bluth2016: 'Bluth, K., Gaylord, S. A., Campo, R. A., Mullarkey, M. C. & Hobbs, L. (2016). Making Friends with Yourself: A mixed methods pilot study of a mindful self-compassion program for adolescents. Mindfulness, 7(2), 479–492.',
  vonDerEmbse2013: 'von der Embse, N., Barterian, J. & Segool, N. (2013). Test anxiety interventions for children and adolescents: A systematic review of treatment studies from 2000–2010. Psychology in the Schools, 50(1), 57–71.',
  chung2017: 'Chung, K.-F., Chan, M.-S., Lam, Y.-Y., Lai, C. S.-Y. & Yeung, W.-F. (2017). School-based sleep education programs for short sleep duration in adolescents: A systematic review and meta-analysis. Journal of School Health, 87(6), 401–408.',
  // Förderfach, Wirkungs-Check: Mobbing, Normen, Vorurteile, Netz
  kaerna2013: 'Kärnä, A., Voeten, M., Little, T. D., Alanen, E., Poskiparta, E. & Salmivalli, C. (2013). Effectiveness of the KiVa antibullying program: Grades 1–3 and 7–9. Journal of Educational Psychology, 105(2), 535–551.',
  yeagerFong2015: 'Yeager, D. S., Fong, C. J., Lee, H. Y. & Espelage, D. L. (2015). Declines in efficacy of anti-bullying programs among older adolescents: Theory and a three-level meta-analysis. Journal of Applied Developmental Psychology, 37, 36–51.',
  gaffneyTtofi2019: 'Gaffney, H., Ttofi, M. M. & Farrington, D. P. (2019). Evaluating the effectiveness of school-bullying prevention programs: An updated meta-analytical review. Aggression and Violent Behavior, 45, 111–133.',
  gaffneyFarrington2019: 'Gaffney, H., Farrington, D. P., Espelage, D. L. & Ttofi, M. M. (2019). Are cyberbullying intervention and prevention programs effective? A systematic and meta-analytical review. Aggression and Violent Behavior, 45, 134–153.',
  polanin2012: 'Polanin, J. R., Espelage, D. L. & Pigott, T. D. (2012). A meta-analysis of school-based bullying prevention programs’ effects on bystander intervention behavior. School Psychology Review, 41(1), 47–65.',
  perkinsCraig2011: 'Perkins, H. W., Craig, D. W. & Perkins, J. M. (2011). Using social norms to reduce bullying: A research intervention among adolescents in five middle schools. Group Processes & Intergroup Relations, 14(5), 703–722.',
  paluckShepherd2016: 'Paluck, E. L., Shepherd, H. & Aronow, P. M. (2016). Changing climates of conflict: A social network experiment in 56 schools. Proceedings of the National Academy of Sciences, 113(3), 566–571.',
  paluckPorat2021: 'Paluck, E. L., Porat, R., Clark, C. S. & Green, D. P. (2021). Prejudice reduction: Progress and challenges. Annual Review of Psychology, 72, 533–560.',
  roozenbeek2022: 'Roozenbeek, J., van der Linden, S., Goldberg, B., Rathje, S. & Lewandowsky, S. (2022). Psychological inoculation improves resilience against misinformation on social media. Science Advances, 8(34), eabo6254.',
  // Förderfach, Wirkungs-Check: Suchtprävention, Suizidprävention
  faggiano2008: 'Faggiano, F., Galanti, M. R., Bohrn, K., Burkhart, G., Vigna-Taglianti, F., Cuomo, L. et al. (2008). The effectiveness of a school-based substance abuse prevention program: EU-Dap cluster randomised controlled trial. Preventive Medicine, 47(5), 537–543.',
  faggiano2010: 'Faggiano, F., Vigna-Taglianti, F., Burkhart, G., Bohrn, K., Cuomo, L., Gregori, D. et al. (2010). The effectiveness of a school-based substance abuse prevention program: 18-month follow-up of the EU-Dap cluster randomized controlled trial. Drug and Alcohol Dependence, 108(1–2), 56–64.',
  botvin1995: 'Botvin, G. J., Baker, E., Dusenbury, L., Botvin, E. M. & Diaz, T. (1995). Long-term follow-up results of a randomized drug abuse prevention trial in a white middle-class population. JAMA, 273(14), 1106–1112.',
  hbscLuxemburg2024: 'Catunda, C., Goedert Mendes, F. & Lopes Ferreira, J. (2024). Risk Behaviours in School-aged Children in Luxembourg: Report on the Luxembourg HBSC Survey 2022. Esch-sur-Alzette: Université du Luxembourg.',
  wyman2010: 'Wyman, P. A., Brown, C. H., LoMurray, M., Schmeelk-Cone, K., Petrova, M., Yu, Q. et al. (2010). An outcome evaluation of the Sources of Strength suicide prevention program delivered by adolescent peer leaders in high schools. American Journal of Public Health, 100(9), 1653–1661.',
  robinson2018: 'Robinson, J., Bailey, E., Witt, K., Stefanac, N., Milner, A., Currier, D., Pirkis, J., Condron, P. & Hetrick, S. (2018). What works in youth suicide prevention? A systematic review and meta-analysis. EClinicalMedicine, 4–5, 52–91.',
}

export const QUELLEN_TEXTE = new Set(Object.values(QUELLEN))
