export const meta = {
  name: 'lumo-art-upgrade',
  description: 'Premium art upgrade for LUMO: style bible, cel-shaded rendering + post stack, new stylised characters, premium UI, then art-director review and fixes (Fable agents)',
  phases: [
    { title: 'Style', detail: 'art director writes the style bible from current screenshots', model: 'fable' },
    { title: 'Render+Figuren', detail: 'rendering/post stack and new characters in parallel', model: 'fable' },
    { title: 'UI', detail: 'premium UI pass', model: 'fable' },
    { title: 'Review', detail: 'art director compares against the bible', model: 'fable' },
    { title: 'Fix', detail: 'implement review, final shots', model: 'fable' },
  ],
}
const S = args.scratch
const I = '/home/user/ISA-APP/insel'
const M = 'fable'
const CTX = `PROJECT: "LUMO – die Skills-Insel" (${I}), a three.js open-world island game (ES modules bundled by esbuild into one offline HTML: node build.mjs → dist/index.html) for 12–16-year-olds on school iPads (Safari) and PCs. Read ${I}/DESIGN.md (§1 look, §20 tech, §20a), the conventions at the top of src/game.js and src/core/state.js (plugins, state, debug, tests: tests/lib.mjs, tests/smoke.mjs, tests/shots.mjs, LUMO.debug.teleport/setTimeOfDay/restoreZone/setShot).
THE TEACHER'S VERDICT on the current look: "Sieht noch nicht hochwertig genug aus" — the overall impression still reads as a prototype. Style choice given to us: "whatever looks the MOST high-end". Our decision: a premium stylised look in the spirit of Zelda: Breath of the Wild / Genshin Impact / Sky — cel/toon shading with soft 2–3 band ramps, crisp coloured outlines, rim light, painted gradient skies with anime clouds, bloom on light sources, strong colour grading, clean silhouettes, fewer but better-crafted details — because stylisation looks premium even with procedural geometry. No external assets exist (network: only npm registry); everything is generated in code (you may use three/examples/jsm postprocessing, e.g. EffectComposer, UnrealBloomPass, OutputPass, SMAA/FXAA, and canvas-generated textures). Performance matters: iPad 'medium' tier must stay smooth (post stack reduced on low: no bloom/outlines-lite). Keep public APIs backward compatible (other agents are building quests, dialogue, NPC systems in parallel under src/systems/** and src/content/** — do not edit those; createHumanoid/spawnHumanoid, setAnim, setExpression, setEmotionAura, cosmetics config must keep working). Keep the build green (node build.mjs, npm run test:fast, node tests/smoke.mjs). Do NOT git commit or push. Comments in German. Save screenshots to ${S}/shots/art/ and LOOK at them with the Read tool — judge honestly like a AAA art director.`
const OUT = { type: 'object', properties: { done: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' }, shots: { type: 'array', items: { type: 'string' } }, open: { type: 'array', items: { type: 'string' } } }, required: ['done', 'notes', 'shots', 'open'] }
const commit = (msg) => agent(`In /home/user/ISA-APP run: git add -A insel && git commit -m "${msg}" -m "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_018gV6PaeSbmQbnTJRvrxG3K" (skip if nothing to commit), then git push -u origin claude/youth-game-socio-emotional-ntxd04 (retry up to 4 times with 2/4/8/16 s backoff on network errors). Nothing else. Return the commit hash or "nothing".`, { label: 'commit', model: M, effort: 'low' })

phase('Style')
const bible = await agent(`${CTX}\n\nYou are the ART DIRECTOR. Build the game, take a screenshot set of the current look (title, harbour with NPCs, beach, jungle, cliffs storm, volcano, night, a dialogue, the character close-up, the HUD) and write ${I}/docs/STIL.md (German): a concrete, implementable style bible — palette per region and time of day (hex), shading model (ramp bands, shadow colour tint, rim light), outline rules (width per object class, colour), sky/clouds/fog/water look, vegetation style, character design (proportions ~6.5 heads, head/eye/hair/clothes construction, expressions), prop/building language, VFX (bloom thresholds, sparkles, veil and colour wave), UI style (typography, glass panels, name tags small and elegant, buttons, speech bubbles), camera/composition rules, and a prioritised gap list "current → target" with the 15 biggest quality problems. Return a short summary.`, { label: 'art-director:bible', phase: 'Style', model: M, schema: OUT })

phase('Render+Figuren')
const [render, figuren] = await parallel([
  () => agent(`${CTX}\n\nYOUR TASK (Rendering): implement docs/STIL.md for the world: toon/cel shading for all lit materials (terrain, vegetation, props, water, characters via the shared material path / veil.patch), outlines (inverted hull or post edge-detect — choose what looks best and performs on iPad), rim light, painted sky + clouds, fog/atmosphere, post stack (bloom on emissive/light, colour grade, vignette, AA) with quality tiers, better terrain surfacing (smooth colour transitions, paths, ambient occlusion baked into vertex colours), water in the new style. You own: src/engine/renderer.js, src/world/** (except content-specific region files under src/regions/**), src/props/kit/** materials. Iterate with screenshots until it clearly looks premium.`, { label: 'render', phase: 'Render+Figuren', model: M, schema: OUT }),
  () => agent(`${CTX}\n\nYOUR TASK (Characters): implement docs/STIL.md for characters: replace the blocky box look with smooth stylised figures (rounded torso/limbs from lathe/capsule shapes, proper hands, shoes, layered hair shells with outlines, clothes with simple folds), anime-inspired faces via canvas textures (eyes with highlights, blinking, brows and mouths for the expression API), cel-shaded skin/cloth using the shared toon material, more appealing proportions (~6.5 heads), better idle/walk/run animation curves (secondary motion in hair/backpack), elegant small name tags. Keep all existing APIs and cosmetics/config options working (src/actors/humanoid*, humanoid/**). You own src/actors/humanoid.js and src/actors/humanoid/**. Show a line-up of 8 diverse characters and the player close-up in screenshots.`, { label: 'figuren', phase: 'Render+Figuren', model: M, schema: OUT }),
])
await commit('LUMO: Grafik-Upgrade – Cel-Shading, Post-Effekte, neue Figuren')

phase('UI')
const ui = await agent(`${CTX}\n\nYOUR TASK (UI): implement the UI part of docs/STIL.md: typography (embed a nice free font as base64 via npm @fontsource if it helps; OFL only), glass/frosted panels, HUD buttons, joystick, compass, name tags, speech bubbles, choice tiles, journal/Tagebuch pages, title screen, loading screen, toasts — premium, consistent, readable for weak readers, touch-friendly. Only visual changes (CSS and view code in src/ui/** and src/styles.css); do not change logic in src/systems/**. Screenshots before/after.`, { label: 'ui', phase: 'UI', model: M, schema: OUT })
await commit('LUMO: Grafik-Upgrade – hochwertige Oberfläche')

phase('Review')
const review = await agent(`${CTX}\n\nYou are the ART DIRECTOR again. Compare the current build against docs/STIL.md with a fresh screenshot set (same shots as before, day/night, iPad landscape + portrait). Is it now clearly premium? List the remaining gaps as prioritised, concrete fixes with files. Be strict. Do not edit files.`, { label: 'art-director:review', phase: 'Review', model: M, schema: { type: 'object', properties: { verdict: { type: 'string' }, score: { type: 'number' }, fixes: { type: 'array', items: { type: 'object', properties: { priority: { type: 'number' }, files: { type: 'string' }, change: { type: 'string' } }, required: ['priority', 'files', 'change'] } } }, required: ['verdict', 'score', 'fixes'] } })

phase('Fix')
const fix = await agent(`${CTX}\n\nImplement the art director's fixes (all priority 1–2, then others if feasible), iterate with screenshots, keep tests green, and produce a final showcase set in ${S}/shots/art/final/ (harbour day, harbour night, beach after colour wave, jungle, cliffs storm, volcano, character line-up, dialogue, title). Fixes:\n${JSON.stringify(review ? review.fixes : [], null, 1)}`, { label: 'art-fix', phase: 'Fix', model: M, schema: OUT })
await commit('LUMO: Grafik-Upgrade – Feinschliff nach Art-Review')
return { bible: bible && bible.notes, render: render && render.done, figuren: figuren && figuren.done, ui: ui && ui.done, review: review && { score: review.score, verdict: review.verdict }, fix: fix && fix.shots }
