export const meta = {
  name: 'lumo-hub-prep',
  description: 'Prepare the CDSE-Hub connection: ELDiB-to-island mapping, drop-in hub card module with focus code/QR, focus-code import in LUMO',
  phases: [{ title: 'HubPrep', model: 'fable' }],
}
const I = '/home/user/ISA-APP/insel'
phase('HubPrep')
const r = await agent(`PROJECT: LUMO – die Skills-Insel (${I}; read DESIGN.md incl. §10 teacher mode and §20a, ROADMAP.md, the conventions at the top of src/game.js and src/core/state.js). The teacher's CDSE Hub (a separate single-file web app for staff, developed in ANOTHER session — you must NOT touch the Klassebuch repo) shows per student ELDiB support goals (codes V-n, K-n, SOZ-n, KOG-n; same numbers as the French catalogue COMP/COMM/SOC/COG; see /tmp/claude-0/-home-user/f6080bde-1b7f-57ff-8c41-9f899e920847/scratchpad/txt/ISA-APP__Eldib_fr_catalogue_CDSE.txt) and weekly goals. Goal: in the student profile the hub tells the teacher which LUMO world is the priority for this youth (e.g. "Gefühls-Dschungel – Empathie"), and the youth gets a focus code/QR that makes that world glow in the game.
BUILD (plain JS, German texts, no personal data ever leaves the hub; the code contains NO names):
1. ${I}/integration/eldib-insel.js (+ .json export): mapping of all ELDiB codes relevant for 12–16 (stages II–V) → LUMO region(s)/ability/quest ids with a short German reason ("SOZ-37 Einfühlen → Gefühls-Dschungel, Kraft Empathie-Blick"). Faithful to the item meanings (own paraphrases, never catalogue text).
2. ${I}/integration/hub-karte.js: a framework-free drop-in module for the hub: window.LUMO_HUB.renderFokusKarte(container, {eldibGoals:[codes], wochenziele:[strings]}) → renders a compact card "Insel-Fokus" (top 1–2 worlds with reason and matching quests), plus buttons to show a FOCUS CODE (short, typeable, e.g. FOKUS-DSCHUNGEL-7K with checksum) and a QR code (inline tiny QR encoder, MIT, no network) encoding the game URL + #fokus=<code>. Include a small demo page ${I}/integration/demo.html and a German installation guide ${I}/integration/EINBAU-HUB.md written for another Claude session that maintains the hub (where to call it in a student profile, data mapping, privacy notes).
3. In the game: a focus code (via code entry or #fokus= in the URL) marks the priority world(s) on the map, adds a personal "Wochen-Fokus" mission in the Tagebuch and a gentle glow at that region; state stored per save; teacher can clear it. Add tests. Keep the build green (node build.mjs, npm run test:fast, node tests/smoke.mjs).
Do NOT commit. Return what you built and how the hub session should integrate it.`, { label: 'hub-prep', phase: 'HubPrep', model: 'fable', effort: 'medium', schema: { type: 'object', properties: { built: { type: 'array', items: { type: 'string' } }, integration_note: { type: 'string' }, tests: { type: 'string' } }, required: ['built', 'integration_note', 'tests'] } })
await agent(`In /home/user/ISA-APP run: git add -A insel && git commit -m "LUMO: Vorbereitung CDSE-Hub (ELDiB → Insel-Fokus, Hub-Karte, Fokus-Code)" -m "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>" -m "Claude-Session: https://claude.ai/code/session_018gV6PaeSbmQbnTJRvrxG3K" (skip if nothing to commit), then git push -u origin claude/youth-game-socio-emotional-ntxd04 (retry up to 4 times on network errors). Return the hash.`, { label: 'commit', model: 'fable', effort: 'low' })
return r
